"use client";

import React, { useEffect, useId, useRef, useState } from "react";
import mermaid from "mermaid";

let mermaidReady = false;

function ensureMermaidInitialized() {
  if (mermaidReady) return;
  mermaidReady = true;
  mermaid.initialize({
    startOnLoad: false,
    theme: "base",
    themeVariables: {
      background: "#0A0826",
      mainBkg: "#1F1B47",
      nodeBorder: "#2A2560",
      clusterBkg: "#110F33",
      titleColor: "#F5F5FA",
      edgeLabelBackground: "#0A0826",
      lineColor: "#6B6890",
      textColor: "#B8B5D1",
      primaryColor: "#1F1B47",
      primaryTextColor: "#F5F5FA",
      primaryBorderColor: "#2A2560",
      secondaryColor: "#110F33",
      tertiaryColor: "#0A0826",
      fontFamily: "monospace",
      fontSize: "13px",
      labelBackground: "#0A0826",
      actorBorder: "#2A2560",
      actorBkg: "#1F1B47",
      actorTextColor: "#F5F5FA",
      activationBorderColor: "#0AFFD4",
      activationBkgColor: "rgba(10,255,212,0.08)",
      sequenceNumberColor: "#0AFFD4",
      signalColor: "#6B6890",
      signalTextColor: "#B8B5D1",
    },
  });
}

interface DiagramProps {
  children: string;
  caption?: string;
}

export function Diagram({ children, caption }: DiagramProps): React.JSX.Element {
  const rawId = useId();
  const diagramId = `mermaid-${rawId.replace(/:/g, "")}`;
  const containerRef = useRef<HTMLDivElement>(null);
  const [error, setError] = useState<string | null>(null);
  const [rendered, setRendered] = useState(false);

  useEffect(() => {
    ensureMermaidInitialized();
    const el = containerRef.current;
    if (!el) return;

    let cancelled = false;
    setError(null);
    setRendered(false);

    mermaid
      .render(diagramId, children.trim())
      .then(({ svg }) => {
        if (cancelled || !containerRef.current) return;
        // SAFETY: output is SVG generated by mermaid from admin-authored diagram syntax.
        // Mermaid sanitizes its own output — no arbitrary JS or event handlers.
        containerRef.current.innerHTML = svg;
        setRendered(true);
      })
      .catch(() => {
        if (cancelled) return;
        setError("Syntaxe de diagramme invalide");
      });

    return () => {
      cancelled = true;
    };
  }, [children, diagramId]);

  return (
    <figure
      style={{
        margin: "32px 0",
        background: "#0A0826",
        border: "1px solid #1F1B47",
        borderLeft: "3px solid #0AFFD4",
        padding: "24px",
        overflowX: "auto",
      }}
    >
      {!rendered && error === null && (
        <div
          style={{
            fontFamily: "var(--font-mono, monospace)",
            fontSize: 12,
            color: "#44406B",
            padding: "4px 0",
          }}
        >
          Chargement du diagramme…
        </div>
      )}
      {error !== null && (
        <div
          style={{
            fontFamily: "var(--font-mono, monospace)",
            fontSize: 12,
            color: "#FF4757",
            padding: "4px 0",
          }}
        >
          ✗ {error}
        </div>
      )}
      <div
        ref={containerRef}
        style={{
          display: rendered ? "flex" : "none",
          justifyContent: "center",
        }}
      />
      {caption !== undefined && (
        <figcaption
          style={{
            marginTop: 16,
            fontFamily: "var(--font-mono, monospace)",
            fontSize: 11,
            letterSpacing: "0.06em",
            color: "#6B6890",
            textAlign: "center",
          }}
        >
          {caption}
        </figcaption>
      )}
    </figure>
  );
}
