/**
 * What the commands of the lessons do, option by option, for the explanation
 * a learner asks of a line typed in a terminal (explain.ts).
 *
 * The lessons expect about two hundred different commands, the first of
 * them by far: cat, grep, ls, systemctl, echo, ip, apt, head, mkdir,
 * journalctl, tail, diff, tar, sed, chmod, find, ssh. Each entry says what
 * the command does, what its usual options mean, whether an option takes a
 * value, and how its words are read when they do not follow the usual
 * `-x --long` rule: `ps aux`, `tar xzvf`, `find -name`, `dd if=`,
 * `chmod 640`, `kill -9`. In French: these are the words the learner reads.
 */

export interface OptionSpec {
  /** The spellings: ["-a", "--all"]. */
  names: readonly string[];
  role: string;
  /** The name of the value the option takes, when it takes one: "N", "fichier". */
  value?: string;
}

/**
 * How a command reads its words. `gnu` is the usual rule; `ps` and `tar`
 * take a cluster of letters without a dash (`ps aux`, `tar xzvf`); `find`
 * takes predicates (`-name x`, `-exec ... \;`); `dd` takes `key=value`;
 * `chmod` takes a mode first; `kill` takes a signal (`-9`, `-TERM`).
 */
export type OptionStyle = "gnu" | "ps" | "tar" | "find" | "dd" | "chmod" | "kill";

export interface CommandSpec {
  name: string;
  summary: string;
  options?: readonly OptionSpec[];
  /** The verbs of systemctl, ip, apt, git...: the first word that is not an option. */
  subcommands?: Readonly<Record<string, string>>;
  /** What the other words are: "les fichiers à afficher". */
  operands?: string;
  style?: OptionStyle;
  /** sudo, time, xargs, watch: another command follows, with its own words. */
  prefix?: boolean;
}

function opt(names: string, role: string, value?: string): OptionSpec {
  const list = names.split(" ");
  return value === undefined ? { names: list, role } : { names: list, role, value };
}

const RECURSIVE = opt(
  "-R --recursive",
  "applique aussi au contenu des dossiers, à tous les niveaux",
);
const VERBOSE = opt("-v --verbose", "dit ce qu'elle fait, fichier par fichier");
const HUMAN = opt("-h --human-readable", "les tailles lisibles : K, M, G");
const HELP = opt("--help", "affiche l'aide de la commande");

export const COMMANDS: readonly CommandSpec[] = [
  // ── Files and directories ────────────────────────────────────────────────
  {
    name: "ls",
    summary: "liste le contenu d'un dossier",
    operands: "les dossiers ou fichiers à lister (le dossier courant sans rien)",
    options: [
      opt("-l", "le format long : droits, liens, propriétaire, groupe, taille, date, nom"),
      opt("-a --all", "aussi les fichiers cachés, ceux dont le nom commence par un point"),
      opt("-A --almost-all", "les fichiers cachés aussi, sauf . et .."),
      HUMAN,
      opt("-R --recursive", "descend dans les sous-dossiers"),
      opt("-t", "trie par date de modification, le plus récent en premier"),
      opt("-r --reverse", "inverse l'ordre du tri"),
      opt("-S", "trie par taille, la plus grande en premier"),
      opt("-d --directory", "le dossier lui-même, pas son contenu"),
      opt("-i --inode", "le numéro d'inode de chaque entrée"),
      opt("-n", "les identifiants numériques (UID, GID) à la place des noms"),
      opt("-1", "un nom par ligne"),
      opt("--color", "colore selon le type : dossier, exécutable, lien"),
      HELP,
    ],
  },
  {
    name: "cd",
    summary: "change de dossier courant",
    operands: "le dossier où aller (ton dossier personnel sans rien, le précédent avec -)",
  },
  { name: "pwd", summary: "affiche le chemin du dossier courant" },
  {
    name: "cat",
    summary: "affiche le contenu des fichiers, bout à bout",
    operands: "les fichiers à afficher",
    options: [
      opt("-n --number", "numérote les lignes"),
      opt("-b", "numérote les lignes non vides seulement"),
      opt(
        "-A --show-all",
        "montre les caractères invisibles : tabulations (^I), fins de ligne ($)",
      ),
      opt("-E", "marque la fin de chaque ligne d'un $"),
      opt("-T", "montre les tabulations comme ^I"),
      opt("-s", "fond les lignes vides qui se suivent en une seule"),
    ],
  },
  {
    name: "less",
    summary: "affiche un fichier page par page (q pour quitter, / pour chercher, G pour la fin)",
    operands: "le fichier à lire",
    options: [
      opt("-N", "numérote les lignes"),
      opt("-S", "ne replie pas les lignes longues"),
      opt("+F", "suit le fichier au fil de l'eau, comme tail -f"),
    ],
  },
  { name: "more", summary: "affiche un fichier page par page", operands: "le fichier à lire" },
  {
    name: "head",
    summary: "affiche le début d'un fichier (dix lignes sans option)",
    operands: "les fichiers à lire",
    options: [
      opt("-n --lines", "le nombre de lignes à afficher", "N"),
      opt("-c --bytes", "le nombre d'octets à afficher", "N"),
      opt("-q", "sans l'en-tête quand il y a plusieurs fichiers"),
    ],
  },
  {
    name: "tail",
    summary: "affiche la fin d'un fichier (dix lignes sans option)",
    operands: "les fichiers à lire",
    options: [
      opt("-n --lines", "le nombre de lignes à afficher", "N"),
      opt("-f --follow", "suit le fichier : affiche ce qui s'y ajoute, jusqu'à Ctrl+C"),
      opt("-F", "suit le fichier même s'il est recréé, comme à la rotation d'un journal"),
      opt("-c --bytes", "le nombre d'octets à afficher", "N"),
    ],
  },
  {
    name: "touch",
    summary: "crée un fichier vide, ou met à jour la date d'un fichier qui existe",
    operands: "les fichiers à créer ou à dater",
    options: [
      opt("-c", "ne crée rien si le fichier manque"),
      opt("-d", "la date à poser plutôt que maintenant", "date"),
    ],
  },
  {
    name: "mkdir",
    summary: "crée un dossier",
    operands: "les dossiers à créer",
    options: [
      opt(
        "-p --parents",
        "crée aussi les dossiers intermédiaires, sans se plaindre si tout existe déjà",
      ),
      opt("-m --mode", "les droits du dossier créé", "mode"),
      VERBOSE,
    ],
  },
  {
    name: "rmdir",
    summary: "supprime un dossier vide",
    operands: "les dossiers à supprimer",
    options: [opt("-p", "supprime aussi les dossiers parents devenus vides")],
  },
  {
    name: "cp",
    summary: "copie des fichiers ou des dossiers",
    operands: "la source, puis la destination (le dernier mot)",
    options: [
      opt("-r -R --recursive", "copie un dossier avec tout son contenu"),
      opt("-i --interactive", "demande avant d'écraser"),
      opt("-f --force", "écrase sans demander"),
      opt("-n --no-clobber", "n'écrase jamais un fichier existant"),
      opt("-p", "garde les droits, le propriétaire et les dates"),
      opt("-a --archive", "une copie fidèle : récursive, droits, liens et dates gardés"),
      opt("-u --update", "ne copie que si la source est plus récente"),
      VERBOSE,
    ],
  },
  {
    name: "mv",
    summary: "déplace ou renomme des fichiers et des dossiers",
    operands: "la source, puis la destination (le dernier mot)",
    options: [
      opt("-i --interactive", "demande avant d'écraser"),
      opt("-f --force", "écrase sans demander"),
      opt("-n --no-clobber", "n'écrase jamais un fichier existant"),
      VERBOSE,
    ],
  },
  {
    name: "rm",
    summary: "supprime des fichiers, sans corbeille",
    operands: "les fichiers ou dossiers à supprimer",
    options: [
      opt("-r -R --recursive", "supprime un dossier avec tout son contenu"),
      opt("-f --force", "sans confirmation, et sans erreur si le fichier manque"),
      opt("-i", "demande confirmation pour chaque fichier"),
      opt("-d", "supprime un dossier vide"),
      VERBOSE,
    ],
  },
  {
    name: "ln",
    summary: "crée un lien vers un fichier",
    operands: "la cible, puis le nom du lien",
    options: [
      opt(
        "-s --symbolic",
        "un lien symbolique : un raccourci vers un chemin, plutôt qu'un second nom du même fichier",
      ),
      opt("-f --force", "remplace le lien s'il existe déjà"),
      opt("-v", "dit ce qu'elle crée"),
    ],
  },
  {
    name: "find",
    style: "find",
    summary: "cherche des fichiers selon des critères, en descendant dans les dossiers",
    operands: "le dossier de départ, puis les critères et les actions",
    options: [
      opt("-name", "le nom (un motif, sensible à la casse)", "motif"),
      opt("-iname", "le nom, sans distinguer majuscules et minuscules", "motif"),
      opt("-path", "le chemin complet (un motif)", "motif"),
      opt("-regex", "le chemin complet (une expression régulière)", "regex"),
      opt("-type", "le type : f fichier, d dossier, l lien symbolique", "type"),
      opt("-size", "la taille : +10M plus de 10 Mo, -1k moins d'un Ko", "taille"),
      opt(
        "-mtime",
        "modifié il y a N jours : -7 depuis moins de sept jours, +30 depuis plus de trente",
        "N",
      ),
      opt("-mmin", "modifié il y a N minutes", "N"),
      opt("-newer", "modifié après ce fichier", "fichier"),
      opt("-user", "appartenant à cet utilisateur", "nom"),
      opt("-group", "appartenant à ce groupe", "nom"),
      opt(
        "-perm",
        "ayant ces droits : 644 exactement, -u+s avec au moins le setuid, /222 écrivable par quelqu'un",
        "mode",
      ),
      opt("-empty", "vide : un fichier de zéro octet ou un dossier sans rien"),
      opt("-maxdepth", "ne descend pas plus de N niveaux", "N"),
      opt("-mindepth", "ignore les N premiers niveaux", "N"),
      opt("-xdev", "reste sur le même système de fichiers"),
      opt("-L", "suit les liens symboliques"),
      opt(
        "-exec",
        "exécute une commande sur chaque résultat : {} est le fichier, \\; termine la commande",
        "commande",
      ),
      opt("-delete", "supprime ce qui est trouvé"),
      opt("-print", "affiche les chemins trouvés (l'action par défaut)"),
      opt("-print0", "affiche les chemins séparés par un octet nul, pour xargs -0"),
      opt("-ls", "affiche les résultats au format long"),
      opt("-o -or", "ou : l'un ou l'autre des critères"),
      opt("-a -and", "et : les deux critères"),
      opt("-not !", "non : inverse le critère qui suit"),
    ],
  },
  {
    name: "tree",
    summary: "dessine l'arborescence d'un dossier",
    operands: "le dossier à dessiner",
    options: [
      opt("-a", "aussi les fichiers cachés"),
      opt("-L", "la profondeur maximale", "N"),
      opt("-d", "les dossiers seulement"),
      opt("-p", "avec les droits"),
      opt("-h", "avec les tailles lisibles"),
    ],
  },
  {
    name: "file",
    summary: "devine le type d'un fichier à son contenu, pas à son nom",
    operands: "les fichiers à examiner",
    options: [opt("-i", "le type MIME"), opt("-b", "sans le nom du fichier devant")],
  },
  {
    name: "stat",
    summary: "affiche tout ce que le système sait d'un fichier : taille, droits, inode, dates",
    operands: "les fichiers",
    options: [
      opt(
        "-c",
        "le format de sortie : %a les droits en octal, %U le propriétaire, %s la taille",
        "format",
      ),
      opt("-f", "le système de fichiers qui porte le fichier, plutôt que le fichier"),
    ],
  },
  {
    name: "readlink",
    summary: "affiche la cible d'un lien symbolique",
    operands: "le lien",
    options: [opt("-f", "le chemin absolu final, tous les liens résolus")],
  },
  {
    name: "du",
    summary: "mesure l'espace occupé par des fichiers ou des dossiers",
    operands: "les dossiers à mesurer (le courant sans rien)",
    options: [
      opt("-s --summarize", "un total par argument, sans le détail des sous-dossiers"),
      HUMAN,
      opt("-a --all", "les fichiers aussi, pas seulement les dossiers"),
      opt("-d --max-depth", "ne détaille pas plus de N niveaux", "N"),
      opt("-c --total", "ajoute un total général"),
      opt("-x", "reste sur le même système de fichiers"),
    ],
  },
  {
    name: "df",
    summary: "affiche l'espace libre des systèmes de fichiers montés",
    operands: "un chemin, pour le seul système de fichiers qui le porte",
    options: [
      HUMAN,
      opt("-T", "avec le type de chaque système de fichiers"),
      opt("-i --inodes", "les inodes plutôt que les octets"),
      opt("-a --all", "tous, y compris les pseudo-systèmes de fichiers"),
    ],
  },
  {
    name: "chmod",
    style: "chmod",
    summary: "change les droits d'un fichier ou d'un dossier",
    operands: "les fichiers à modifier",
    options: [RECURSIVE, VERBOSE, opt("-c --changes", "dit seulement ce qui a changé")],
  },
  {
    name: "chown",
    summary: "change le propriétaire, et le groupe, d'un fichier",
    operands: "utilisateur, ou utilisateur:groupe, puis les fichiers",
    options: [
      RECURSIVE,
      opt("-v", "dit ce qu'elle change"),
      opt("-h", "le lien lui-même, pas sa cible"),
    ],
  },
  {
    name: "chgrp",
    summary: "change le groupe d'un fichier",
    operands: "le groupe, puis les fichiers",
    options: [RECURSIVE, opt("-v", "dit ce qu'elle change")],
  },
  {
    name: "umask",
    summary: "affiche ou fixe le masque des droits retirés aux fichiers créés",
    operands:
      "le masque en octal : 022 retire l'écriture au groupe et aux autres, 077 retire tout aux autres",
    options: [opt("-S", "le masque en lettres plutôt qu'en octal")],
  },
  {
    name: "getfacl",
    summary: "affiche les droits étendus (ACL) d'un fichier",
    operands: "les fichiers",
  },
  {
    name: "setfacl",
    summary: "pose des droits étendus (ACL) : des droits de plus pour un utilisateur ou un groupe",
    operands: "les fichiers",
    options: [
      opt("-m --modify", "ajoute ou modifie une entrée : u:alice:rw-", "entrée"),
      opt("-x --remove", "retire une entrée", "entrée"),
      opt("-b --remove-all", "retire toutes les ACL"),
      opt("-R", "applique aussi au contenu des dossiers"),
      opt("-d --default", "les droits par défaut d'un dossier, hérités par ce qu'on y crée"),
    ],
  },
  {
    name: "lsattr",
    summary: "affiche les attributs étendus d'un fichier : i immuable, a ajout seulement",
    operands: "les fichiers",
  },
  {
    name: "chattr",
    summary: "change les attributs étendus d'un fichier",
    operands: "+i rend immuable, -i le redevient, +a n'autorise que l'ajout ; puis les fichiers",
    options: [opt("-R", "applique aussi au contenu des dossiers")],
  },

  // ── Text ────────────────────────────────────────────────────────────────
  {
    name: "grep",
    summary: "cherche un motif dans du texte et affiche les lignes qui le contiennent",
    operands: "le motif, puis les fichiers où chercher (l'entrée standard sans fichier)",
    options: [
      opt("-i --ignore-case", "sans distinguer majuscules et minuscules"),
      opt(
        "-r -R --recursive",
        "cherche dans tous les fichiers d'un dossier, sous-dossiers compris",
      ),
      opt("-n --line-number", "avec le numéro de chaque ligne"),
      opt("-v --invert-match", "les lignes qui ne contiennent pas le motif"),
      opt("-c --count", "le nombre de lignes qui correspondent, pas les lignes"),
      opt(
        "-l --files-with-matches",
        "les noms des fichiers qui contiennent le motif, pas les lignes",
      ),
      opt("-L", "les noms des fichiers qui ne le contiennent pas"),
      opt("-w --word-regexp", "le motif comme un mot entier"),
      opt("-x", "le motif comme la ligne entière"),
      opt("-E --extended-regexp", "une expression régulière étendue : +, ?, |, ()"),
      opt("-F --fixed-strings", "un texte tel quel, pas une expression régulière"),
      opt("-o --only-matching", "la partie qui correspond, pas la ligne entière"),
      opt("-A --after-context", "N lignes après chaque correspondance", "N"),
      opt("-B --before-context", "N lignes avant chaque correspondance", "N"),
      opt("-C --context", "N lignes autour de chaque correspondance", "N"),
      opt("-e", "un motif (pour en donner plusieurs, ou un qui commence par un tiret)", "motif"),
      opt("-h", "sans le nom du fichier devant chaque ligne"),
      opt("-H", "avec le nom du fichier devant chaque ligne"),
      opt("-q --quiet", "n'affiche rien : seul le code de retour dit s'il y a eu correspondance"),
      opt("-s", "ne se plaint pas des fichiers illisibles"),
      opt("--color", "surligne ce qui correspond"),
      opt("--include", "ne cherche que dans les fichiers dont le nom correspond", "motif"),
      opt("--exclude", "ignore les fichiers dont le nom correspond", "motif"),
    ],
  },
  {
    name: "egrep",
    summary: "grep -E : cherche une expression régulière étendue",
    operands: "le motif, puis les fichiers",
  },
  {
    name: "fgrep",
    summary: "grep -F : cherche un texte tel quel",
    operands: "le texte, puis les fichiers",
  },
  {
    name: "sed",
    summary: "transforme du texte ligne par ligne : remplacer, supprimer, extraire",
    operands:
      "le programme (s/avant/après/ remplace, /motif/d supprime, 5p affiche la ligne 5), puis les fichiers",
    options: [
      opt("-i --in-place", "modifie le fichier lui-même, au lieu d'afficher le résultat"),
      opt("-n --quiet", "n'affiche que ce que le programme demande (p)"),
      opt("-e --expression", "un programme (pour en donner plusieurs)", "programme"),
      opt("-E -r", "des expressions régulières étendues"),
      opt("-s", "traite chaque fichier à part"),
    ],
  },
  {
    name: "awk",
    summary: "traite du texte colonne par colonne : $1 est la première, $NF la dernière",
    operands: "le programme ('{print $1}', '/motif/ {…}'), puis les fichiers",
    options: [
      opt("-F", "le séparateur de colonnes (une espace par défaut)", "séparateur"),
      opt("-v", "une variable donnée au programme : -v seuil=10", "var=valeur"),
      opt("-f", "lit le programme dans ce fichier", "fichier"),
    ],
  },
  {
    name: "sort",
    summary: "trie des lignes",
    operands: "les fichiers à trier (l'entrée standard sans rien)",
    options: [
      opt("-n --numeric-sort", "trie par valeur numérique (10 après 9)"),
      opt("-r --reverse", "ordre inverse"),
      opt("-k --key", "trie sur cette colonne : -k 2 la deuxième, -k 2,2n numérique", "N"),
      opt("-t --field-separator", "le séparateur de colonnes", "caractère"),
      opt("-u --unique", "garde une seule ligne parmi les identiques"),
      opt("-h --human-numeric-sort", "trie des tailles lisibles : 1K, 2M, 3G"),
      opt("-f --ignore-case", "sans distinguer majuscules et minuscules"),
      opt("-o --output", "écrit le résultat dans ce fichier", "fichier"),
      opt("-s --stable", "garde l'ordre d'origine entre lignes égales"),
    ],
  },
  {
    name: "uniq",
    summary: "retire les doublons qui se suivent (d'où le sort juste avant)",
    operands: "le fichier à lire",
    options: [
      opt("-c --count", "compte chaque ligne"),
      opt("-d --repeated", "seulement les lignes répétées"),
      opt("-u --unique", "seulement les lignes uniques"),
      opt("-i --ignore-case", "sans distinguer majuscules et minuscules"),
    ],
  },
  {
    name: "cut",
    summary: "extrait des colonnes ou des caractères de chaque ligne",
    operands: "les fichiers à lire",
    options: [
      opt("-d --delimiter", "le séparateur de colonnes (une tabulation par défaut)", "caractère"),
      opt("-f --fields", "les colonnes à garder : 1, 1,3 ou 2-4", "liste"),
      opt("-c --characters", "les caractères à garder, par position : 1-10", "liste"),
      opt("-b --bytes", "les octets à garder", "liste"),
      opt("-s --only-delimited", "ignore les lignes sans séparateur"),
    ],
  },
  {
    name: "tr",
    summary: "remplace ou supprime des caractères",
    operands: "le jeu de départ, puis le jeu d'arrivée : 'a-z' 'A-Z' met en majuscules",
    options: [
      opt("-d --delete", "supprime les caractères du jeu"),
      opt("-s --squeeze-repeats", "fond les répétitions en un seul caractère"),
      opt("-c --complement", "tout sauf les caractères du jeu"),
    ],
  },
  {
    name: "wc",
    summary: "compte les lignes, les mots et les caractères",
    operands: "les fichiers à compter (l'entrée standard sans rien)",
    options: [
      opt("-l --lines", "les lignes seulement"),
      opt("-w --words", "les mots seulement"),
      opt("-c --bytes", "les octets seulement"),
      opt("-m --chars", "les caractères seulement"),
      opt("-L", "la longueur de la ligne la plus longue"),
    ],
  },
  {
    name: "diff",
    summary: "compare deux fichiers ligne par ligne et montre ce qui change",
    operands: "le premier fichier, puis le second (< vient du premier, > du second)",
    options: [
      opt(
        "-u --unified",
        "le format unifié, celui des patchs : - retiré, + ajouté, avec du contexte",
      ),
      opt("-r --recursive", "compare deux dossiers, fichier par fichier"),
      opt("-q --brief", "dit seulement si les fichiers diffèrent"),
      opt("-i --ignore-case", "sans distinguer majuscules et minuscules"),
      opt("-w --ignore-all-space", "ignore les espaces"),
      opt("-y --side-by-side", "les deux fichiers côte à côte"),
      opt("-N", "un fichier absent compte comme vide"),
    ],
  },
  {
    name: "tee",
    summary: "écrit ce qu'elle reçoit à la fois à l'écran et dans un fichier",
    operands: "le fichier où écrire aussi",
    options: [opt("-a --append", "ajoute à la fin du fichier au lieu de l'écraser")],
  },
  {
    name: "xargs",
    prefix: true,
    summary: "construit une commande avec ce qu'elle lit en entrée, mot par mot",
    operands: "la commande à lancer, suivie de ce qui est lu",
    options: [
      opt("-0 --null", "les entrées sont séparées par un octet nul (find -print0)"),
      opt("-n --max-args", "au plus N arguments par commande lancée", "N"),
      opt("-I", "remplace ce texte par chaque entrée, à l'endroit voulu", "texte"),
      opt("-p --interactive", "demande avant chaque commande"),
      opt("-t", "affiche chaque commande avant de la lancer"),
      opt("-r --no-run-if-empty", "ne lance rien si l'entrée est vide"),
    ],
  },
  {
    name: "echo",
    summary: "affiche ses arguments",
    operands: "le texte à afficher (les variables y sont remplacées)",
    options: [
      opt("-n", "sans retour à la ligne à la fin"),
      opt("-e", "interprète les séquences : \\n retour à la ligne, \\t tabulation"),
      opt("-E", "n'interprète pas les séquences"),
    ],
  },
  {
    name: "printf",
    summary: "affiche du texte selon un format, comme en C",
    operands:
      "le format (%s texte, %d nombre, %05.2f décimal, \\n retour à la ligne), puis les valeurs",
  },
  {
    name: "base64",
    summary: "encode en Base64, ou décode",
    operands: "le fichier à lire (l'entrée standard sans rien)",
    options: [
      opt("-d --decode", "décode au lieu d'encoder"),
      opt("-w --wrap", "la longueur des lignes (0 pour une seule)", "N"),
    ],
  },
  {
    name: "xxd",
    summary: "affiche un fichier en hexadécimal, ou reconstruit un fichier depuis l'hexadécimal",
    operands: "le fichier à lire",
    options: [
      opt("-p", "l'hexadécimal nu, sans adresses ni colonne texte"),
      opt("-r", "le sens inverse : de l'hexadécimal vers les octets"),
      opt("-l", "ne lit que N octets", "N"),
      opt("-s", "commence à ce décalage", "décalage"),
      opt("-c", "N octets par ligne", "N"),
      opt("-b", "en binaire plutôt qu'en hexadécimal"),
    ],
  },
  {
    name: "od",
    summary: "affiche un fichier octet par octet, en octal, hexadécimal ou caractères",
    operands: "le fichier à lire",
    options: [
      opt("-A", "le format des adresses : x hexadécimal, d décimal, n aucune", "format"),
      opt("-t", "le format des octets : x1 hexadécimal, c caractères, d1 décimal", "format"),
      opt("-c", "les octets comme des caractères"),
      opt("-N", "ne lit que N octets", "N"),
    ],
  },
  {
    name: "sha256sum",
    summary: "calcule l'empreinte SHA-256 d'un fichier, ou vérifie des empreintes",
    operands: "les fichiers à hacher",
    options: [
      opt("-c --check", "vérifie les empreintes listées dans le fichier donné"),
      opt("-b", "lit en mode binaire"),
    ],
  },
  {
    name: "sha1sum",
    summary: "calcule l'empreinte SHA-1 d'un fichier (dépassée pour la sécurité)",
    operands: "les fichiers",
    options: [opt("-c --check", "vérifie des empreintes listées")],
  },
  {
    name: "md5sum",
    summary: "calcule l'empreinte MD5 d'un fichier (dépassée pour la sécurité)",
    operands: "les fichiers",
    options: [opt("-c --check", "vérifie des empreintes listées")],
  },
  {
    name: "strings",
    summary: "extrait le texte lisible d'un fichier binaire",
    operands: "les fichiers",
    options: [opt("-n", "la longueur minimale d'une chaîne", "N")],
  },

  // ── Archives and copies ─────────────────────────────────────────────────
  {
    name: "tar",
    style: "tar",
    summary: "rassemble des fichiers dans une archive, ou les en sort",
    operands: "les fichiers ou dossiers à archiver, ou à extraire",
    options: [
      opt("-c --create", "crée une archive"),
      opt("-x --extract", "extrait une archive"),
      opt("-t --list", "liste le contenu d'une archive sans l'extraire"),
      opt("-v --verbose", "liste les fichiers au fur et à mesure"),
      opt("-f --file", "le fichier d'archive", "archive"),
      opt("-z --gzip", "compresse ou décompresse avec gzip (.tar.gz)"),
      opt("-j --bzip2", "compresse ou décompresse avec bzip2 (.tar.bz2)"),
      opt("-J --xz", "compresse ou décompresse avec xz (.tar.xz)"),
      opt("-C --directory", "se place dans ce dossier avant d'archiver ou d'extraire", "dossier"),
      opt("-p --preserve-permissions", "garde les droits à l'extraction"),
      opt("--exclude", "laisse de côté ce qui correspond au motif", "motif"),
      opt("-r --append", "ajoute des fichiers à une archive existante"),
      opt("-u --update", "ajoute les fichiers plus récents que ceux de l'archive"),
    ],
  },
  {
    name: "gzip",
    summary: "compresse un fichier (il devient fichier.gz)",
    operands: "les fichiers à compresser",
    options: [
      opt("-d --decompress", "décompresse"),
      opt("-k --keep", "garde le fichier d'origine"),
      opt("-9 --best", "compression maximale, plus lente"),
      opt("-1 --fast", "compression rapide, moins forte"),
      opt("-l --list", "liste la taille avant et après"),
      opt("-r --recursive", "compresse les fichiers d'un dossier"),
      opt("-c --stdout", "écrit sur la sortie standard, sans toucher au fichier"),
      VERBOSE,
    ],
  },
  {
    name: "gunzip",
    summary: "décompresse un fichier .gz",
    operands: "les fichiers à décompresser",
    options: [
      opt("-k --keep", "garde le fichier compressé"),
      opt("-c", "écrit sur la sortie standard"),
      opt("-l", "liste la taille avant et après"),
    ],
  },
  {
    name: "zcat",
    summary: "affiche un fichier .gz sans le décompresser sur le disque",
    operands: "les fichiers",
  },
  {
    name: "zip",
    summary: "crée une archive zip",
    operands: "l'archive, puis les fichiers à y mettre",
    options: [
      opt("-r", "avec le contenu des dossiers"),
      opt("-e", "chiffrée par mot de passe"),
      opt("-q", "silencieuse"),
    ],
  },
  {
    name: "unzip",
    summary: "extrait une archive zip",
    operands: "l'archive",
    options: [
      opt("-l", "liste le contenu sans extraire"),
      opt("-d", "extrait dans ce dossier", "dossier"),
      opt("-o", "écrase sans demander"),
    ],
  },
  {
    name: "rsync",
    summary:
      "synchronise des fichiers, en local ou vers une machine distante, en ne copiant que ce qui change",
    operands:
      "la source, puis la destination (un / final sur la source copie son contenu, pas le dossier)",
    options: [
      opt("-a --archive", "copie fidèle : récursive, droits, dates, liens, propriétaire"),
      opt("-v --verbose", "liste les fichiers transférés"),
      opt("-z --compress", "compresse pendant le transfert"),
      opt("-n --dry-run", "montre ce qui serait fait, sans rien faire"),
      opt("--delete", "supprime à destination ce qui n'est plus dans la source"),
      opt("-e", "la commande de connexion : -e ssh", "commande"),
      opt("-P", "la progression, et reprend un transfert interrompu"),
      opt("--progress", "la progression de chaque fichier"),
      opt("--exclude", "laisse de côté ce qui correspond au motif", "motif"),
      opt("-h", "les tailles lisibles"),
      opt("-u --update", "ne remplace pas un fichier plus récent à destination"),
    ],
  },
  {
    name: "dd",
    style: "dd",
    summary:
      "copie des octets d'une source vers une destination, bloc par bloc : disques, images, fichiers de test",
    operands: "des paires clé=valeur",
  },

  // ── Processes and system ────────────────────────────────────────────────
  {
    name: "ps",
    style: "ps",
    summary: "liste les processus",
    options: [
      opt("-e -A", "tous les processus"),
      opt("-f", "le format complet : utilisateur, parent, heure, commande"),
      opt("-u", "les processus de cet utilisateur", "utilisateur"),
      opt("-p", "ce processus seulement", "PID"),
      opt("-o", "les colonnes à afficher : pid,user,%cpu,cmd", "colonnes"),
      opt("--sort", "trie sur cette colonne : -%mem", "colonne"),
      opt("--forest", "l'arbre des processus"),
    ],
  },
  {
    name: "top",
    summary: "affiche les processus en direct, les plus gourmands en premier (q pour quitter)",
    options: [
      opt("-u", "les processus de cet utilisateur", "utilisateur"),
      opt("-p", "ce processus seulement", "PID"),
      opt("-n", "N rafraîchissements, puis quitte", "N"),
      opt("-b", "en mode texte, pour un fichier ou un tube"),
      opt("-d", "le délai entre deux rafraîchissements", "secondes"),
    ],
  },
  { name: "htop", summary: "top en plus lisible : couleurs, défilement, arbre, tri à la souris" },
  {
    name: "pstree",
    summary: "dessine l'arbre des processus",
    operands: "un PID ou un utilisateur, pour sa branche",
    options: [opt("-p", "avec les PID"), opt("-u", "avec les utilisateurs")],
  },
  {
    name: "kill",
    style: "kill",
    summary: "envoie un signal à un processus (TERM, une demande d'arrêt propre, sans option)",
    operands: "les PID des processus visés",
    options: [
      opt("-l", "liste les signaux"),
      opt("-s", "le signal à envoyer, par son nom", "signal"),
    ],
  },
  {
    name: "pkill",
    style: "kill",
    summary: "envoie un signal aux processus trouvés par leur nom",
    operands: "le nom, ou un motif",
    options: [
      opt("-f", "cherche dans la ligne de commande entière"),
      opt("-u", "les processus de cet utilisateur", "utilisateur"),
    ],
  },
  {
    name: "pgrep",
    summary: "affiche les PID des processus trouvés par leur nom",
    operands: "le nom, ou un motif",
    options: [
      opt("-l", "avec le nom"),
      opt("-f", "cherche dans la ligne de commande entière"),
      opt("-u", "les processus de cet utilisateur", "utilisateur"),
      opt("-a", "avec la ligne de commande"),
    ],
  },
  {
    name: "killall",
    style: "kill",
    summary: "envoie un signal à tous les processus de ce nom",
    operands: "les noms des programmes",
  },
  {
    name: "jobs",
    summary: "liste les tâches lancées depuis ce shell : en arrière-plan ou suspendues",
    options: [opt("-l", "avec les PID")],
  },
  {
    name: "bg",
    summary: "reprend une tâche suspendue, en arrière-plan",
    operands: "le numéro de la tâche : %1",
  },
  {
    name: "fg",
    summary: "ramène une tâche au premier plan",
    operands: "le numéro de la tâche : %1",
  },
  {
    name: "nohup",
    prefix: true,
    summary:
      "lance une commande qui survit à la fermeture du terminal (sa sortie va dans nohup.out)",
    operands: "la commande",
  },
  {
    name: "nice",
    prefix: true,
    summary: "lance une commande avec une priorité plus basse",
    operands: "la commande",
    options: [opt("-n", "la politesse, de -20 (prioritaire) à 19 (en dernier)", "N")],
  },
  {
    name: "renice",
    summary: "change la priorité d'un processus qui tourne",
    operands: "la politesse, puis le PID",
    options: [opt("-n", "la politesse", "N"), opt("-p", "le PID", "PID")],
  },
  {
    name: "watch",
    prefix: true,
    summary: "relance une commande à intervalle régulier et affiche son résultat",
    operands: "la commande",
    options: [
      opt("-n --interval", "toutes les N secondes (2 sans rien)", "N"),
      opt("-d --differences", "surligne ce qui change"),
    ],
  },
  {
    name: "time",
    prefix: true,
    summary: "mesure le temps que prend une commande",
    operands: "la commande",
  },
  { name: "sleep", summary: "attend", operands: "la durée : 5 secondes, 2m minutes, 1h" },
  {
    name: "free",
    summary: "affiche la mémoire vive et le swap, utilisés et libres",
    options: [
      HUMAN,
      opt("-m", "en mégaoctets"),
      opt("-g", "en gigaoctets"),
      opt("-s", "rafraîchit toutes les N secondes", "N"),
    ],
  },
  {
    name: "uptime",
    summary: "depuis quand la machine tourne, et sa charge sur 1, 5 et 15 minutes",
  },
  { name: "nproc", summary: "le nombre de processeurs disponibles" },
  { name: "lscpu", summary: "décrit le processeur : cœurs, architecture, caches" },
  {
    name: "lspci",
    summary: "liste les périphériques PCI : carte graphique, réseau, contrôleurs",
    options: [opt("-v", "avec le détail"), opt("-k", "avec le pilote utilisé")],
  },
  { name: "lsusb", summary: "liste les périphériques USB", options: [opt("-v", "avec le détail")] },
  { name: "lsmod", summary: "liste les modules chargés dans le noyau" },
  {
    name: "modprobe",
    summary: "charge un module du noyau, ou le retire",
    operands: "le module",
    options: [opt("-r", "retire le module")],
  },
  {
    name: "dmesg",
    summary: "affiche les messages du noyau : matériel détecté, erreurs de disque, modules",
    options: [
      opt("-T", "avec des dates lisibles"),
      opt("-w", "suit les nouveaux messages"),
      opt("-l", "ce niveau seulement : err, warn", "niveau"),
      opt("-H", "lisible, page par page"),
    ],
  },
  {
    name: "uname",
    summary: "le nom du système et du noyau",
    options: [
      opt("-a --all", "tout : noyau, version, machine, architecture"),
      opt("-r", "la version du noyau"),
      opt("-m", "l'architecture : x86_64, aarch64"),
      opt("-n", "le nom de la machine"),
      opt("-s", "le nom du noyau"),
    ],
  },
  {
    name: "hostname",
    summary: "affiche ou change le nom de la machine",
    operands: "le nouveau nom",
    options: [opt("-I", "ses adresses IP"), opt("-f", "le nom complet, avec le domaine")],
  },
  {
    name: "hostnamectl",
    summary: "affiche ou change le nom de la machine, de façon durable (systemd)",
    subcommands: { status: "l'état : nom, système, noyau", "set-hostname": "change le nom" },
    operands: "le nom",
  },
  {
    name: "date",
    summary: "affiche la date et l'heure, ou les fixe",
    operands: "un format : +%Y-%m-%d, +%H:%M",
    options: [
      opt("-u", "en temps universel (UTC)"),
      opt("-d", "une autre date que maintenant : 'yesterday', '2026-01-10'", "date"),
      opt("-s", "fixe la date du système", "date"),
      opt("-R", "au format des e-mails"),
      opt("-I", "au format ISO 8601"),
    ],
  },
  {
    name: "timedatectl",
    summary: "affiche ou règle l'heure, le fuseau et la synchronisation (systemd)",
    subcommands: {
      status: "l'état de l'horloge",
      "set-timezone": "change le fuseau",
      "set-ntp": "active ou coupe la synchronisation",
      "list-timezones": "liste les fuseaux",
    },
  },
  { name: "cal", summary: "affiche un calendrier", operands: "le mois et l'année" },
  {
    name: "sysctl",
    summary: "lit ou change un paramètre du noyau en cours d'exécution",
    operands: "le paramètre, ou paramètre=valeur",
    options: [
      opt("-a", "tous les paramètres"),
      opt("-w", "écrit une valeur"),
      opt("-p", "recharge les valeurs d'un fichier de configuration"),
    ],
  },
  {
    name: "ulimit",
    summary: "affiche ou limite les ressources du shell et de ses processus",
    operands: "la nouvelle limite",
    options: [
      opt("-a", "toutes les limites"),
      opt("-n", "le nombre de fichiers ouverts"),
      opt("-u", "le nombre de processus"),
      opt("-c", "la taille des fichiers core"),
      opt("-H", "la limite dure"),
      opt("-S", "la limite souple"),
    ],
  },
  {
    name: "shutdown",
    summary: "arrête ou redémarre la machine, tout de suite ou plus tard",
    operands: "now tout de suite, +10 dans dix minutes, 23:00 à cette heure",
    options: [
      opt("-h", "arrête"),
      opt("-r", "redémarre"),
      opt("-c", "annule un arrêt programmé"),
      opt("-P", "arrête et coupe l'alimentation"),
    ],
  },
  { name: "reboot", summary: "redémarre la machine" },
  { name: "poweroff", summary: "arrête la machine et coupe l'alimentation" },
  { name: "halt", summary: "arrête le système" },
  {
    name: "systemctl",
    summary: "pilote les services et l'état du système (systemd)",
    operands: "le service visé : nginx, ssh, cron",
    subcommands: {
      status: "l'état du service : actif ou non, depuis quand, ses derniers messages",
      start: "démarre le service maintenant",
      stop: "arrête le service maintenant",
      restart: "arrête puis redémarre le service",
      reload: "fait relire sa configuration au service sans l'arrêter",
      enable: "le service démarrera avec la machine",
      disable: "le service ne démarrera plus avec la machine",
      "is-active": "dit seulement si le service tourne",
      "is-enabled": "dit seulement si le service démarre avec la machine",
      mask: "interdit tout démarrage du service, même manuel",
      unmask: "lève l'interdiction",
      "daemon-reload": "fait relire à systemd les fichiers d'unités modifiés",
      "list-units": "liste les unités chargées",
      "list-unit-files": "liste les fichiers d'unités installés et leur état enable",
      "list-timers": "liste les minuteries, l'équivalent systemd de cron",
      "list-dependencies": "les unités dont celle-ci dépend",
      cat: "affiche le fichier d'unité",
      edit: "modifie l'unité par un fichier de surcharge",
      show: "toutes les propriétés de l'unité",
      "show-environment": "l'environnement de systemd",
      "set-default": "la cible de démarrage par défaut",
      "get-default": "la cible de démarrage par défaut",
      isolate: "passe à cette cible, en arrêtant le reste",
      reboot: "redémarre la machine",
      poweroff: "arrête la machine",
      suspend: "met en veille",
      kill: "envoie un signal aux processus du service",
      "reset-failed": "oublie l'état en échec d'un service",
    },
    options: [
      opt("--type -t", "ce type d'unités seulement : service, timer, socket", "type"),
      opt("--state", "cet état seulement : running, failed", "état"),
      opt("--failed", "les unités en échec seulement"),
      opt("--all -a", "aussi les unités inactives"),
      opt("--now", "avec enable ou disable : démarre ou arrête aussi tout de suite"),
      opt("--no-pager", "sans pagination"),
      opt("-l --full", "les lignes entières, sans les couper"),
      opt("--user", "les unités de la session de l'utilisateur, pas celles du système"),
      opt("-f --force", "force l'opération"),
    ],
  },
  {
    name: "journalctl",
    summary: "lit le journal du système (systemd)",
    options: [
      opt("-u --unit", "les messages de ce service", "unité"),
      opt("-f --follow", "suit le journal en direct, jusqu'à Ctrl+C"),
      opt("-n --lines", "les N dernières lignes", "N"),
      opt("-b --boot", "depuis le dernier démarrage (-b -1 : le précédent)"),
      opt("-p --priority", "ce niveau et plus grave : err, warning, info", "niveau"),
      opt("--since", "depuis cette date : '1 hour ago', 'today', '2026-01-10 03:00'", "date"),
      opt("--until", "jusqu'à cette date", "date"),
      opt("-k --dmesg", "les messages du noyau seulement"),
      opt("-x", "avec des explications sur les messages connus"),
      opt("-e --pager-end", "ouvre le journal à la fin"),
      opt("-r --reverse", "le plus récent en premier"),
      opt("-o --output", "le format : short, json, cat", "format"),
      opt("--no-pager", "sans pagination"),
      opt("--disk-usage", "la place occupée par le journal"),
      opt("--vacuum-time", "supprime les entrées plus vieilles que", "durée"),
      opt("--vacuum-size", "ramène le journal sous cette taille", "taille"),
      opt("-g --grep", "les messages qui contiennent ce motif", "motif"),
      opt("--list-boots", "liste les démarrages connus"),
    ],
  },
  {
    name: "systemd-analyze",
    summary: "mesure le démarrage du système",
    subcommands: {
      blame: "les unités classées par temps de démarrage",
      "critical-chain": "la chaîne qui a pris le plus de temps",
      time: "le temps de démarrage total",
      plot: "un graphique SVG du démarrage",
      verify: "vérifie un fichier d'unité",
      security: "l'exposition de chaque service",
    },
  },
  {
    name: "crontab",
    summary: "gère les tâches planifiées de l'utilisateur (cron)",
    operands: "un fichier de tâches à installer",
    options: [
      opt("-e", "ouvre la table pour la modifier"),
      opt("-l", "affiche la table"),
      opt("-r", "supprime la table"),
      opt("-u", "la table de cet utilisateur", "utilisateur"),
    ],
  },
  {
    name: "logger",
    summary: "écrit un message dans le journal du système",
    operands: "le message",
    options: [
      opt("-t --tag", "l'étiquette du message", "étiquette"),
      opt("-p --priority", "la priorité : user.notice, auth.warning", "priorité"),
    ],
  },
  {
    name: "logrotate",
    summary: "fait tourner les journaux selon sa configuration : archive, compresse, supprime",
    operands: "le fichier de configuration",
    options: [
      opt("-d", "simule et explique, sans rien faire"),
      opt("-f", "force la rotation maintenant"),
      opt("-v", "détaille"),
    ],
  },
  {
    name: "syslogd",
    summary: "le démon des journaux de BusyBox",
    options: [opt("-O", "le fichier de journal", "fichier"), opt("-n", "reste au premier plan")],
  },

  // ── Users ───────────────────────────────────────────────────────────────
  {
    name: "sudo",
    prefix: true,
    summary: "exécute la commande en tant que root (ou un autre utilisateur), si tu y es autorisé",
    operands: "la commande",
    options: [
      opt("-u --user", "en tant que cet utilisateur plutôt que root", "utilisateur"),
      opt("-i", "ouvre un shell de connexion de l'utilisateur"),
      opt("-s", "ouvre un shell"),
      opt("-l", "liste ce que tu as le droit de faire"),
      opt("-k", "oublie le mot de passe mémorisé"),
      opt("-E", "garde ton environnement"),
      opt("-v", "renouvelle le délai sans rien lancer"),
    ],
  },
  {
    name: "su",
    summary: "ouvre un shell sous un autre compte (root sans rien)",
    operands: "l'utilisateur",
    options: [
      opt("-", "un shell de connexion : son environnement, son dossier"),
      opt("-l --login", "un shell de connexion"),
      opt("-c", "exécute cette commande, puis revient", "commande"),
      opt("-s", "ce shell plutôt que celui du compte", "shell"),
    ],
  },
  {
    name: "passwd",
    summary: "change un mot de passe (le tien sans rien)",
    operands: "l'utilisateur",
    options: [
      opt("-l", "verrouille le compte"),
      opt("-u", "déverrouille le compte"),
      opt("-d", "supprime le mot de passe"),
      opt("-e", "oblige à le changer à la prochaine connexion"),
      opt("-S", "l'état du mot de passe"),
    ],
  },
  {
    name: "chage",
    summary: "règle l'expiration d'un mot de passe",
    operands: "l'utilisateur",
    options: [
      opt("-l", "affiche les dates"),
      opt("-M", "le nombre de jours maximal entre deux changements", "N"),
      opt("-m", "le nombre de jours minimal", "N"),
      opt("-W", "prévient N jours avant", "N"),
      opt("-E", "la date d'expiration du compte", "date"),
      opt("-d", "la date du dernier changement (0 force un changement)", "date"),
    ],
  },
  {
    name: "id",
    summary: "ton identité : UID, GID et groupes",
    operands: "un autre utilisateur",
    options: [
      opt("-u", "l'UID seulement"),
      opt("-g", "le GID seulement"),
      opt("-G", "tous les groupes"),
      opt("-n", "les noms plutôt que les numéros"),
      opt("-un", "ton nom"),
      opt("-Gn", "les noms de tes groupes"),
    ],
  },
  { name: "whoami", summary: "le nom du compte sous lequel tu travailles" },
  {
    name: "who",
    summary: "qui est connecté, depuis où et depuis quand",
    options: [opt("-a", "tout"), opt("-b", "la date du dernier démarrage")],
  },
  { name: "w", summary: "qui est connecté et ce qu'il fait" },
  {
    name: "last",
    summary: "les dernières connexions, depuis /var/log/wtmp",
    operands: "un utilisateur",
    options: [opt("-n", "les N dernières", "N"), opt("-a", "la provenance en dernière colonne")],
  },
  { name: "groups", summary: "les groupes d'un utilisateur", operands: "l'utilisateur" },
  {
    name: "getent",
    summary: "lit une base du système : passwd, group, hosts",
    operands: "la base, puis la clé : getent passwd alice",
  },
  {
    name: "adduser",
    summary: "crée un utilisateur, avec son dossier et ses questions (Debian)",
    operands: "le nom, ou utilisateur puis groupe pour l'ajouter au groupe",
    options: [
      opt("--disabled-password", "sans mot de passe"),
      opt("--gecos", "le nom complet, sans questions", "texte"),
      opt("--home", "le dossier personnel", "dossier"),
      opt("--shell", "le shell", "shell"),
      opt("-D", "sans mot de passe (BusyBox)"),
      opt("-H", "sans dossier personnel (BusyBox)"),
      opt("-G", "dans ce groupe (BusyBox)", "groupe"),
    ],
  },
  {
    name: "useradd",
    summary: "crée un utilisateur, sans rien demander",
    operands: "le nom",
    options: [
      opt("-m --create-home", "crée le dossier personnel"),
      opt("-s --shell", "le shell", "shell"),
      opt("-G --groups", "les groupes supplémentaires", "groupes"),
      opt("-g --gid", "le groupe principal", "groupe"),
      opt("-d --home-dir", "le dossier personnel", "dossier"),
      opt("-u --uid", "l'UID", "N"),
      opt("-c --comment", "le nom complet", "texte"),
      opt("-e --expiredate", "la date d'expiration", "date"),
    ],
  },
  {
    name: "usermod",
    summary: "modifie un utilisateur",
    operands: "le nom",
    options: [
      opt("-aG", "ajoute aux groupes (-a pour ajouter sans retirer les autres)", "groupes"),
      opt("-G --groups", "les groupes supplémentaires (remplace la liste)", "groupes"),
      opt("-a --append", "ajoute aux groupes au lieu de remplacer"),
      opt("-s --shell", "le shell", "shell"),
      opt("-L --lock", "verrouille le compte"),
      opt("-U --unlock", "déverrouille le compte"),
      opt("-d --home", "le dossier personnel", "dossier"),
      opt("-l --login", "le nouveau nom", "nom"),
      opt("-e --expiredate", "la date d'expiration", "date"),
    ],
  },
  {
    name: "deluser",
    summary: "supprime un utilisateur (Debian), ou le retire d'un groupe",
    operands: "le nom, ou utilisateur puis groupe",
    options: [opt("--remove-home", "supprime aussi son dossier")],
  },
  {
    name: "userdel",
    summary: "supprime un utilisateur",
    operands: "le nom",
    options: [opt("-r --remove", "supprime aussi son dossier et sa boîte mail")],
  },
  {
    name: "groupadd",
    summary: "crée un groupe",
    operands: "le nom",
    options: [opt("-g --gid", "le GID", "N")],
  },
  {
    name: "addgroup",
    summary: "crée un groupe (Debian, BusyBox)",
    operands: "le nom, ou utilisateur puis groupe pour l'y ajouter",
  },
  { name: "groupdel", summary: "supprime un groupe", operands: "le nom" },
  {
    name: "gpasswd",
    summary: "gère les membres d'un groupe",
    operands: "le groupe",
    options: [
      opt("-a", "ajoute cet utilisateur", "utilisateur"),
      opt("-d", "retire cet utilisateur", "utilisateur"),
    ],
  },
  {
    name: "chsh",
    summary: "change le shell de connexion",
    operands: "l'utilisateur",
    options: [opt("-s", "le nouveau shell", "shell")],
  },
  { name: "visudo", summary: "modifie /etc/sudoers en vérifiant la syntaxe avant d'enregistrer" },

  // ── Disks ───────────────────────────────────────────────────────────────
  {
    name: "lsblk",
    summary: "liste les disques et leurs partitions, en arbre",
    operands: "un périphérique : /dev/sda",
    options: [
      opt("-f --fs", "avec le système de fichiers, l'étiquette et l'UUID"),
      opt("-o --output", "les colonnes : NAME,SIZE,TYPE,MOUNTPOINT", "colonnes"),
      opt("-p", "les chemins complets"),
      opt("-d", "les disques sans leurs partitions"),
      opt("-a", "tout, même les périphériques vides"),
    ],
  },
  {
    name: "blkid",
    summary: "les UUID et les types des systèmes de fichiers",
    operands: "un périphérique",
  },
  {
    name: "fdisk",
    summary: "crée ou modifie des partitions (table MBR ou GPT)",
    operands: "le disque : /dev/sdb",
    options: [opt("-l", "liste les disques et leurs partitions, sans rien changer")],
  },
  {
    name: "parted",
    summary: "crée ou modifie des partitions, scriptable",
    operands: "le disque, puis les commandes : mklabel gpt, mkpart, print",
    options: [opt("-l", "liste tous les disques"), opt("-s", "sans question")],
  },
  {
    name: "sfdisk",
    summary: "écrit une table de partitions depuis un script",
    operands: "le disque",
    options: [opt("-l", "liste"), opt("-d", "exporte la table, pour la rejouer")],
  },
  {
    name: "mkfs.ext4",
    summary: "formate une partition en ext4 (tout son contenu est perdu)",
    operands: "la partition : /dev/sdb1",
    options: [
      opt("-L", "l'étiquette du volume", "nom"),
      opt("-m", "la part réservée à root, en pourcentage", "N"),
      opt("-F", "force, même si la partition semble utilisée"),
    ],
  },
  {
    name: "mkfs",
    summary: "formate une partition",
    operands: "la partition",
    options: [opt("-t", "le type : ext4, xfs, vfat", "type")],
  },
  {
    name: "mkswap",
    summary: "prépare une partition ou un fichier comme swap",
    operands: "la partition ou le fichier",
  },
  {
    name: "swapon",
    summary: "active un espace de swap",
    operands: "la partition ou le fichier",
    options: [opt("--show", "le swap actif"), opt("-a", "tout ce que fstab déclare")],
  },
  {
    name: "tune2fs",
    summary: "règle un système de fichiers ext : étiquette, part réservée, vérifications",
    operands: "la partition",
    options: [
      opt("-l", "affiche les paramètres"),
      opt("-L", "l'étiquette", "nom"),
      opt("-m", "la part réservée à root", "N"),
      opt("-c", "une vérification tous les N montages", "N"),
    ],
  },
  {
    name: "fsck",
    summary: "vérifie et répare un système de fichiers démonté",
    operands: "la partition",
    options: [
      opt("-y", "répond oui à toutes les réparations"),
      opt("-n", "vérifie sans réparer"),
      opt("-f", "force la vérification"),
    ],
  },
  {
    name: "mount",
    summary: "monte un système de fichiers dans l'arborescence (tout lister sans rien)",
    operands: "le périphérique, puis le point de montage",
    options: [
      opt("-t", "le type : ext4, vfat, nfs, tmpfs", "type"),
      opt("-o", "les options : ro, noexec, nosuid, remount", "options"),
      opt("-a", "tout ce que fstab déclare"),
      opt("-r", "en lecture seule"),
      opt("--bind", "rend un dossier visible à un second endroit"),
    ],
  },
  {
    name: "umount",
    summary: "démonte un système de fichiers",
    operands: "le point de montage ou le périphérique",
    options: [
      opt("-l", "paresseux : détache maintenant, libère quand plus rien ne l'utilise"),
      opt("-f", "force"),
      opt("-a", "tout"),
    ],
  },
  {
    name: "findmnt",
    summary: "liste les montages, en arbre",
    operands: "un point de montage ou un périphérique",
    options: [
      opt("-t", "ce type seulement", "type"),
      opt("-l", "en liste plutôt qu'en arbre"),
      opt("-D", "avec l'espace utilisé"),
    ],
  },
  {
    name: "cryptsetup",
    summary: "chiffre un volume avec LUKS, et l'ouvre ou le ferme",
    subcommands: {
      luksFormat: "chiffre la partition (tout son contenu est perdu) et pose la phrase de passe",
      luksOpen: "ouvre le volume chiffré sous un nom dans /dev/mapper",
      open: "ouvre le volume chiffré",
      luksClose: "ferme le volume",
      close: "ferme le volume",
      status: "l'état d'un volume ouvert",
      luksDump: "les en-têtes LUKS : emplacements de clés, chiffrement",
      luksAddKey: "ajoute une phrase de passe",
      luksRemoveKey: "retire une phrase de passe",
      luksChangeKey: "change une phrase de passe",
      isLuks: "dit si c'est un volume LUKS",
    },
    operands: "la partition, puis le nom du volume",
  },
  {
    name: "mdadm",
    summary: "gère les grappes RAID logicielles",
    operands: "la grappe (/dev/md0), puis les disques",
    options: [
      opt("--create -C", "crée une grappe"),
      opt("--level -l", "le niveau RAID : 0, 1, 5, 6, 10", "N"),
      opt("--raid-devices -n", "le nombre de disques", "N"),
      opt("--detail -D", "l'état d'une grappe"),
      opt("--examine -E", "l'en-tête RAID d'un disque"),
      opt("--add -a", "ajoute un disque"),
      opt("--remove -r", "retire un disque"),
      opt("--fail -f", "marque un disque en panne"),
      opt("--stop -S", "arrête une grappe"),
      opt("--assemble -A", "réassemble une grappe"),
      opt("--scan -s", "cherche les grappes connues"),
    ],
  },
  { name: "lvs", summary: "liste les volumes logiques LVM" },
  { name: "vgs", summary: "liste les groupes de volumes LVM" },
  { name: "pvs", summary: "liste les volumes physiques LVM" },
  { name: "sync", summary: "écrit sur le disque tout ce qui attend en mémoire" },
  { name: "eject", summary: "éjecte un support amovible", operands: "le périphérique" },

  // ── Network ─────────────────────────────────────────────────────────────
  {
    name: "ip",
    summary: "affiche ou configure le réseau : adresses, interfaces, routes, voisins",
    subcommands: {
      addr: "les adresses IP des interfaces (ip addr show, ip addr add 10.0.0.2/24 dev eth0)",
      address: "les adresses IP des interfaces",
      a: "les adresses IP des interfaces (abréviation)",
      link: "les interfaces et leur état (ip link set eth0 up)",
      l: "les interfaces (abréviation)",
      route: "la table de routage (ip route add default via 10.0.0.1)",
      r: "la table de routage (abréviation)",
      neigh: "la table ARP : les voisins et leurs adresses MAC",
      n: "la table ARP (abréviation)",
      rule: "les règles de routage par source",
      monitor: "suit les changements en direct",
    },
    operands: "l'action puis ses mots : show, add, del, set, dev eth0, via 10.0.0.1",
    options: [
      opt("-4", "IPv4 seulement"),
      opt("-6", "IPv6 seulement"),
      opt("-br --brief", "une ligne par interface"),
      opt("-c --color", "en couleur"),
      opt("-s --stats", "avec les compteurs"),
      opt("-d --details", "avec le détail"),
    ],
  },
  {
    name: "ifconfig",
    summary: "affiche ou configure les interfaces réseau (l'ancienne commande, remplacée par ip)",
    operands: "l'interface, puis l'adresse ou up / down",
    options: [opt("-a", "toutes les interfaces, même inactives")],
  },
  {
    name: "ping",
    summary: "envoie des paquets ICMP à une machine et mesure le temps de réponse",
    operands: "la machine : une adresse IP ou un nom",
    options: [
      opt("-c", "N paquets, puis s'arrête (sans fin sans rien, Ctrl+C)", "N"),
      opt("-i", "l'intervalle entre deux paquets, en secondes", "secondes"),
      opt("-W", "attend au plus N secondes une réponse", "N"),
      opt("-w", "s'arrête après N secondes en tout", "N"),
      opt("-s", "la taille de chaque paquet", "octets"),
      opt("-4", "IPv4"),
      opt("-6", "IPv6"),
      opt("-q", "le résumé seulement"),
    ],
  },
  {
    name: "traceroute",
    summary: "montre les routeurs traversés jusqu'à une machine",
    operands: "la machine",
    options: [
      opt("-n", "les adresses sans résolution de noms"),
      opt("-m", "au plus N sauts", "N"),
      opt("-I", "avec ICMP plutôt qu'UDP"),
      opt("-T", "avec TCP"),
    ],
  },
  { name: "tracepath", summary: "comme traceroute, sans droits root", operands: "la machine" },
  {
    name: "mtr",
    summary: "traceroute et ping en continu",
    operands: "la machine",
    options: [
      opt("-n", "sans résolution de noms"),
      opt("-r", "un rapport puis quitte"),
      opt("-c", "N cycles", "N"),
    ],
  },
  {
    name: "ss",
    summary: "liste les connexions et les ports en écoute (remplace netstat)",
    options: [
      opt("-t", "TCP"),
      opt("-u", "UDP"),
      opt("-l --listening", "les ports en écoute seulement"),
      opt("-p --processes", "avec le processus qui tient le port"),
      opt("-n --numeric", "les numéros, sans résolution de noms"),
      opt("-a --all", "tout : en écoute et connecté"),
      opt("-s", "un résumé"),
      opt("-4", "IPv4"),
      opt("-6", "IPv6"),
      opt(
        "-tulpn",
        "TCP et UDP en écoute, avec le processus, en numérique : la combinaison classique",
      ),
      opt("-tlnp", "TCP en écoute, numérique, avec le processus"),
      opt("-tunap", "tout TCP et UDP, numérique, avec le processus"),
    ],
  },
  {
    name: "netstat",
    summary: "liste les connexions, les ports en écoute et les routes (ancienne commande)",
    options: [
      opt("-t", "TCP"),
      opt("-u", "UDP"),
      opt("-l", "en écoute"),
      opt("-n", "numérique"),
      opt("-p", "avec le processus"),
      opt("-r", "la table de routage"),
      opt("-a", "tout"),
      opt("-i", "les interfaces"),
      opt("-tulpn", "TCP et UDP en écoute, numérique, avec le processus"),
      opt("-tlnp", "TCP en écoute, numérique, avec le processus"),
    ],
  },
  {
    name: "dig",
    summary: "interroge le DNS et montre la réponse en détail",
    operands: "le nom à résoudre, le type (A, AAAA, MX, TXT, NS), @serveur pour en choisir un",
    options: [
      opt("+short", "la réponse seule"),
      opt("+trace", "suit la résolution depuis la racine"),
      opt("+noall", "n'affiche rien, à combiner avec +answer"),
      opt("+answer", "la section réponse"),
      opt("-x", "la résolution inverse d'une adresse IP", "adresse"),
      opt("-t", "le type d'enregistrement", "type"),
      opt("-p", "le port du serveur", "port"),
    ],
  },
  {
    name: "nslookup",
    summary: "interroge le DNS",
    operands: "le nom ou l'adresse, puis le serveur à interroger",
    options: [opt("-type", "le type d'enregistrement : -type=MX", "type")],
  },
  {
    name: "host",
    summary: "interroge le DNS, en bref",
    operands: "le nom ou l'adresse, puis le serveur",
    options: [opt("-t", "le type d'enregistrement", "type"), opt("-a", "tout")],
  },
  {
    name: "resolvectl",
    summary: "la résolution de noms de systemd",
    subcommands: {
      status: "les serveurs DNS en service",
      query: "résout un nom",
      statistics: "les compteurs",
      "flush-caches": "vide le cache",
    },
  },
  {
    name: "nmcli",
    summary: "pilote NetworkManager : connexions, Wi-Fi, appareils",
    subcommands: {
      device: "les appareils réseau (nmcli device status, nmcli device wifi list)",
      dev: "les appareils (abréviation)",
      connection: "les connexions configurées (nmcli connection up Maison)",
      con: "les connexions (abréviation)",
      general: "l'état général",
      radio: "la radio Wi-Fi : on, off",
      networking: "le réseau : on, off",
    },
    operands: "l'action puis ses mots : status, show, up, down, modify",
  },
  {
    name: "curl",
    summary: "envoie une requête HTTP (ou autre) et affiche la réponse",
    operands: "l'URL",
    options: [
      opt("-s --silent", "sans barre de progression ni messages"),
      opt("-S --show-error", "montre quand même les erreurs"),
      opt("-o --output", "écrit la réponse dans ce fichier", "fichier"),
      opt("-O --remote-name", "écrit la réponse dans un fichier du nom de l'URL"),
      opt("-I --head", "les en-têtes seulement (HEAD)"),
      opt("-i --include", "les en-têtes avec le corps"),
      opt("-L --location", "suit les redirections"),
      opt("-X --request", "la méthode : GET, POST, PUT, DELETE", "méthode"),
      opt("-H --header", "un en-tête à envoyer : 'Content-Type: application/json'", "en-tête"),
      opt("-d --data", "le corps envoyé (POST)", "données"),
      opt("-u --user", "identifiant:mot de passe", "compte"),
      opt("-k --insecure", "accepte un certificat invalide (dangereux)"),
      opt("-v --verbose", "montre tout l'échange"),
      opt("-A --user-agent", "le User-Agent annoncé", "texte"),
      opt("-b --cookie", "les cookies envoyés", "cookies"),
      opt("-c --cookie-jar", "enregistre les cookies reçus dans ce fichier", "fichier"),
      opt("-w --write-out", "affiche une valeur à la fin : %{http_code}", "format"),
      opt("-x --proxy", "passe par ce proxy", "proxy"),
      opt("--resolve", "force une adresse pour un nom", "hôte:port:adresse"),
      opt("-m --max-time", "abandonne après N secondes", "N"),
      opt("-f --fail", "échoue sans rien afficher sur une erreur HTTP"),
    ],
  },
  {
    name: "wget",
    summary: "télécharge un fichier depuis une URL",
    operands: "l'URL",
    options: [
      opt("-O --output-document", "l'enregistre sous ce nom", "fichier"),
      opt("-q --quiet", "sans messages"),
      opt("-c --continue", "reprend un téléchargement interrompu"),
      opt("-r --recursive", "suit les liens et télécharge le site"),
      opt("-P --directory-prefix", "dans ce dossier", "dossier"),
      opt("--no-check-certificate", "accepte un certificat invalide (dangereux)"),
      opt("-b --background", "en arrière-plan"),
      opt("-S --server-response", "affiche les en-têtes reçus"),
      opt("--spider", "vérifie que l'URL répond, sans télécharger"),
    ],
  },
  {
    name: "ssh",
    summary: "ouvre une session sur une machine distante, chiffrée",
    operands: "utilisateur@machine, puis une commande à y exécuter",
    options: [
      opt("-p --port", "le port du serveur (22 sans rien)", "port"),
      opt("-i", "la clé privée à utiliser", "fichier"),
      opt("-l", "l'utilisateur", "utilisateur"),
      opt("-v", "détaille la connexion, pour comprendre un échec"),
      opt("-X", "transporte l'affichage graphique"),
      opt(
        "-L",
        "redirige un port local vers la machine distante : 8080:localhost:80",
        "port:hôte:port",
      ),
      opt("-R", "redirige un port distant vers ici", "port:hôte:port"),
      opt("-D", "un proxy SOCKS sur ce port", "port"),
      opt("-N", "sans commande ni shell : pour les redirections seules"),
      opt("-f", "passe en arrière-plan une fois connecté"),
      opt("-t", "force un terminal"),
      opt("-o", "une option de configuration : StrictHostKeyChecking=no", "option"),
      opt("-J", "passe par cette machine intermédiaire", "hôte"),
      opt("-C", "compresse"),
      opt("-q", "silencieux"),
    ],
  },
  {
    name: "scp",
    summary: "copie des fichiers vers ou depuis une machine distante, par SSH",
    operands: "la source, puis la destination : fichier utilisateur@machine:/chemin",
    options: [
      opt("-r", "un dossier avec son contenu"),
      opt("-P", "le port du serveur", "port"),
      opt("-i", "la clé privée", "fichier"),
      opt("-p", "garde les dates et les droits"),
      opt("-C", "compresse"),
      opt("-q", "silencieux"),
    ],
  },
  {
    name: "sftp",
    summary: "transfère des fichiers par SSH, en session interactive",
    operands: "utilisateur@machine",
    options: [opt("-P", "le port", "port"), opt("-i", "la clé privée", "fichier")],
  },
  {
    name: "ssh-keygen",
    summary: "crée une paire de clés SSH, ou en manipule une",
    options: [
      opt("-t", "le type : ed25519, rsa", "type"),
      opt("-b", "la taille en bits (rsa : 4096)", "N"),
      opt("-f", "le fichier de la clé", "fichier"),
      opt("-C", "un commentaire, souvent une adresse e-mail", "texte"),
      opt("-N", "la phrase de passe (vide : aucune)", "phrase"),
      opt("-p", "change la phrase de passe"),
      opt("-l", "l'empreinte d'une clé"),
      opt("-y", "la clé publique depuis la privée"),
      opt("-R", "retire une machine du fichier known_hosts", "hôte"),
    ],
  },
  {
    name: "ssh-copy-id",
    summary:
      "installe ta clé publique sur une machine distante, pour s'y connecter sans mot de passe",
    operands: "utilisateur@machine",
    options: [opt("-i", "la clé à installer", "fichier"), opt("-p", "le port", "port")],
  },
  {
    name: "ssh-add",
    summary: "confie une clé privée à l'agent SSH, qui la garde déverrouillée",
    operands: "la clé",
    options: [
      opt("-l", "liste les clés chargées"),
      opt("-d", "retire une clé"),
      opt("-D", "retire toutes les clés"),
    ],
  },
  {
    name: "ssh-agent",
    summary: "lance l'agent qui garde les clés SSH déverrouillées",
    options: [opt("-s", "affiche les variables à charger dans le shell")],
  },
  {
    name: "sshd",
    summary: "le serveur SSH",
    options: [
      opt("-t", "teste la configuration sans démarrer"),
      opt("-T", "affiche la configuration effective"),
      opt("-p", "le port", "port"),
      opt("-f", "le fichier de configuration", "fichier"),
      opt("-D", "reste au premier plan"),
      opt("-d", "mode débogage"),
    ],
  },
  {
    name: "nc",
    summary: "netcat : ouvre une connexion brute, ou écoute un port",
    operands: "la machine, puis le port",
    options: [
      opt("-l", "écoute au lieu de se connecter"),
      opt("-p", "le port local", "port"),
      opt("-v", "détaille"),
      opt("-z", "teste seulement si le port est ouvert, sans envoyer"),
      opt("-u", "UDP"),
      opt("-w", "délai d'attente", "secondes"),
      opt("-n", "sans résolution de noms"),
      opt("-e", "lance ce programme sur la connexion", "programme"),
    ],
  },
  {
    name: "netcat",
    summary: "nc : une connexion brute, ou un port en écoute",
    operands: "la machine, puis le port",
  },
  {
    name: "nmap",
    summary: "scanne des machines et leurs ports",
    operands: "la cible : une adresse, un nom, un réseau 10.0.0.0/24",
    options: [
      opt("-sS", "scan SYN : des demi-connexions, discret, root nécessaire"),
      opt("-sT", "scan par connexion complète"),
      opt("-sU", "scan UDP"),
      opt("-sV", "devine les versions des services"),
      opt("-sC", "lance les scripts par défaut"),
      opt("-O", "devine le système d'exploitation"),
      opt("-A", "tout : versions, système, scripts, traceroute"),
      opt("-p", "les ports : 80, 22-443, - pour tous", "ports"),
      opt("-p-", "tous les ports"),
      opt("-Pn", "sans ping préalable : suppose la machine allumée"),
      opt("-sn", "ping seulement : quelles machines répondent"),
      opt("-n", "sans résolution de noms"),
      opt("-v", "détaille"),
      opt("-T4", "plus rapide (T0 lent et discret, T5 agressif)"),
      opt("-oN", "enregistre le rapport dans ce fichier", "fichier"),
      opt("-oA", "enregistre dans tous les formats", "base"),
      opt("--script", "lance ces scripts NSE", "scripts"),
      opt("-iL", "lit les cibles dans ce fichier", "fichier"),
    ],
  },
  {
    name: "tcpdump",
    summary: "capture les paquets qui passent sur une interface",
    operands: "un filtre : port 80, host 10.0.0.5, tcp",
    options: [
      opt("-i", "l'interface (any pour toutes)", "interface"),
      opt("-n", "sans résolution de noms"),
      opt("-nn", "sans résolution des noms ni des ports"),
      opt("-c", "N paquets, puis s'arrête", "N"),
      opt("-w", "enregistre la capture dans ce fichier (.pcap)", "fichier"),
      opt("-r", "lit une capture", "fichier"),
      opt("-v", "détaille"),
      opt("-X", "le contenu des paquets en hexadécimal et en texte"),
      opt("-A", "le contenu des paquets en texte"),
      opt("-s", "la longueur capturée par paquet (0 : tout)", "N"),
      opt("-e", "avec les adresses MAC"),
    ],
  },
  {
    name: "arp",
    summary: "la table ARP (ancienne commande, remplacée par ip neigh)",
    options: [opt("-a", "toutes les entrées"), opt("-n", "numérique")],
  },
  {
    name: "iptables",
    summary: "les règles du pare-feu du noyau (netfilter)",
    operands: "la chaîne (INPUT, OUTPUT, FORWARD), puis la règle",
    options: [
      opt("-L --list", "liste les règles"),
      opt("-A --append", "ajoute une règle à la fin de la chaîne", "chaîne"),
      opt("-I --insert", "insère une règle au début", "chaîne"),
      opt("-D --delete", "supprime une règle", "chaîne"),
      opt("-F --flush", "vide une chaîne"),
      opt("-P --policy", "la politique par défaut d'une chaîne : DROP, ACCEPT", "chaîne"),
      opt("-p --protocol", "le protocole : tcp, udp, icmp", "protocole"),
      opt("-s --source", "l'adresse source", "adresse"),
      opt("-d --destination", "l'adresse de destination", "adresse"),
      opt("--dport", "le port de destination", "port"),
      opt("--sport", "le port source", "port"),
      opt("-j --jump", "ce qu'on fait du paquet : ACCEPT, DROP, REJECT, LOG", "cible"),
      opt("-i --in-interface", "l'interface d'entrée", "interface"),
      opt("-o --out-interface", "l'interface de sortie", "interface"),
      opt("-m --match", "un module de correspondance : state, conntrack", "module"),
      opt("--state", "l'état de la connexion : NEW, ESTABLISHED, RELATED", "états"),
      opt("-n --numeric", "numérique"),
      opt("-v --verbose", "avec les compteurs"),
      opt("-t --table", "la table : filter, nat, mangle", "table"),
      opt("--line-numbers", "avec les numéros des règles"),
    ],
  },
  {
    name: "nft",
    summary: "les règles du pare-feu nftables",
    operands: "list ruleset, add rule, flush ruleset",
  },
  {
    name: "ufw",
    summary: "le pare-feu simple d'Ubuntu, au-dessus de netfilter",
    subcommands: {
      status: "l'état et les règles (status verbose, status numbered)",
      enable: "active le pare-feu",
      disable: "coupe le pare-feu",
      allow:
        "autorise : un port (22), un service (ssh), depuis une adresse (from 10.0.0.0/24 to any port 22)",
      deny: "refuse en silence",
      reject: "refuse en répondant",
      delete: "supprime une règle : delete allow 80, delete 3",
      default: "la politique par défaut : default deny incoming",
      reset: "efface toutes les règles",
      reload: "recharge les règles",
      logging: "le niveau de journalisation",
      show: "des informations : show added",
      limit: "autorise avec limitation de débit (contre la force brute)",
      insert: "insère une règle à ce rang",
    },
    operands: "l'action, puis ses mots : 22/tcp, from, to, port, proto",
  },
  {
    name: "firewall-cmd",
    summary: "le pare-feu firewalld (Fedora, CentOS)",
    options: [
      opt("--list-all", "tout ce qui est ouvert dans la zone"),
      opt("--add-port", "ouvre un port : 80/tcp", "port"),
      opt("--remove-port", "ferme un port", "port"),
      opt("--add-service", "ouvre un service : http", "service"),
      opt("--permanent", "de façon durable, à recharger"),
      opt("--reload", "recharge les règles durables"),
      opt("--zone", "la zone visée", "zone"),
      opt("--state", "l'état du pare-feu"),
    ],
  },
  {
    name: "openssl",
    summary: "la boîte à outils cryptographique : certificats, clés, chiffrement, empreintes",
    subcommands: {
      req: "une demande de certificat, ou un certificat autosigné",
      x509: "lit ou convertit un certificat (-in cert.pem -text -noout)",
      genrsa: "génère une clé RSA",
      genpkey: "génère une clé privée",
      rsa: "lit ou convertit une clé RSA",
      s_client: "se connecte à un serveur TLS et montre son certificat (-connect hôte:443)",
      s_server: "un serveur TLS de test",
      enc: "chiffre ou déchiffre un fichier (-aes-256-cbc, -d)",
      dgst: "calcule une empreinte ou une signature",
      rand: "des octets aléatoires (-hex 16)",
      passwd: "hache un mot de passe",
      verify: "vérifie une chaîne de certificats",
      pkcs12: "convertit vers ou depuis le format PKCS#12 (.p12, .pfx)",
      version: "la version",
    },
    operands: "les mots de la sous-commande : -in, -out, -connect",
  },

  // ── Services and packages ───────────────────────────────────────────────
  {
    name: "nginx",
    summary: "le serveur web nginx",
    options: [
      opt("-t", "teste la configuration sans démarrer"),
      opt("-T", "teste et affiche la configuration"),
      opt(
        "-s",
        "envoie un signal : reload recharge, stop arrête, quit arrête proprement",
        "signal",
      ),
      opt("-c", "le fichier de configuration", "fichier"),
      opt("-v", "la version"),
      opt("-V", "la version et les options de compilation"),
    ],
  },
  {
    name: "apachectl",
    summary: "pilote le serveur web Apache",
    subcommands: {
      configtest: "teste la configuration",
      start: "démarre",
      stop: "arrête",
      restart: "redémarre",
      graceful: "redémarre sans couper les connexions",
      status: "l'état",
    },
  },
  {
    name: "apache2ctl",
    summary: "pilote le serveur web Apache (Debian)",
    subcommands: {
      configtest: "teste la configuration",
      start: "démarre",
      stop: "arrête",
      restart: "redémarre",
      graceful: "redémarre sans couper les connexions",
      status: "l'état",
    },
  },
  { name: "a2ensite", summary: "active un site Apache (Debian)", operands: "le site" },
  { name: "a2enmod", summary: "active un module Apache (Debian)", operands: "le module" },
  { name: "a2dissite", summary: "désactive un site Apache", operands: "le site" },
  {
    name: "apt",
    summary: "gère les paquets Debian et Ubuntu",
    subcommands: {
      update: "rafraîchit la liste des paquets disponibles (ne met rien à jour)",
      upgrade: "met à jour les paquets installés",
      "full-upgrade": "met à jour, en acceptant d'installer ou de retirer des dépendances",
      "dist-upgrade": "comme full-upgrade",
      install: "installe des paquets",
      remove: "retire des paquets, en gardant leur configuration",
      purge: "retire des paquets avec leur configuration",
      autoremove: "retire les dépendances devenues inutiles",
      search: "cherche un paquet par mots-clés",
      show: "la fiche d'un paquet",
      list: "liste des paquets (--installed, --upgradable)",
      policy: "les versions disponibles et leur origine",
      clean: "vide le cache des paquets téléchargés",
      "edit-sources": "modifie les dépôts",
      hold: "bloque un paquet à sa version",
      unhold: "débloque un paquet",
    },
    operands: "les paquets",
    options: [
      opt("-y --yes", "répond oui aux questions"),
      opt("--no-install-recommends", "sans les paquets recommandés"),
      opt("--dry-run -s", "simule"),
      opt("--installed", "les paquets installés seulement"),
      opt("--upgradable", "les paquets à mettre à jour seulement"),
      opt("-q", "moins de sortie"),
      opt("--reinstall", "réinstalle"),
    ],
  },
  {
    name: "apt-get",
    summary: "gère les paquets Debian et Ubuntu (l'outil d'origine, pour les scripts)",
    subcommands: {
      update: "rafraîchit la liste des paquets",
      upgrade: "met à jour",
      "dist-upgrade": "met à jour, dépendances comprises",
      install: "installe",
      remove: "retire",
      purge: "retire avec la configuration",
      autoremove: "retire les dépendances inutiles",
      clean: "vide le cache",
      autoclean: "vide le cache des versions dépassées",
      "build-dep": "installe ce qu'il faut pour compiler un paquet",
      source: "télécharge les sources",
    },
    operands: "les paquets",
    options: [
      opt("-y --yes", "répond oui"),
      opt("--no-install-recommends", "sans les recommandés"),
      opt("-s --simulate", "simule"),
      opt("-q", "moins de sortie"),
      opt("-f --fix-broken", "répare les dépendances cassées"),
    ],
  },
  {
    name: "apt-cache",
    summary: "interroge le cache des paquets",
    subcommands: {
      search: "cherche",
      show: "la fiche d'un paquet",
      policy: "les versions disponibles",
      depends: "les dépendances",
      rdepends: "qui dépend de ce paquet",
    },
    operands: "le paquet",
  },
  {
    name: "dpkg",
    summary: "l'outil de base des paquets Debian : fichiers .deb, base des paquets installés",
    operands: "le paquet ou le fichier .deb",
    options: [
      opt("-i --install", "installe un fichier .deb"),
      opt("-r --remove", "retire un paquet"),
      opt("-P --purge", "retire avec la configuration"),
      opt("-l --list", "liste les paquets installés (avec un motif)"),
      opt("-L --listfiles", "les fichiers d'un paquet installé"),
      opt("-S --search", "quel paquet fournit ce fichier"),
      opt("-s --status", "l'état d'un paquet"),
      opt("-c --contents", "le contenu d'un .deb"),
      opt("-I --info", "la fiche d'un .deb"),
      opt("--configure", "termine la configuration (-a : tous)"),
      opt("--get-selections", "la liste des paquets et leur état"),
    ],
  },
  {
    name: "dpkg-reconfigure",
    summary: "repose les questions de configuration d'un paquet",
    operands: "le paquet",
  },
  {
    name: "snap",
    summary: "gère les paquets snap",
    subcommands: {
      install: "installe",
      remove: "retire",
      list: "liste",
      refresh: "met à jour",
      find: "cherche",
      info: "la fiche",
    },
    operands: "le paquet",
  },
  {
    name: "dnf",
    summary: "gère les paquets Fedora et RHEL",
    subcommands: {
      install: "installe",
      remove: "retire",
      update: "met à jour",
      upgrade: "met à jour",
      search: "cherche",
      info: "la fiche",
      list: "liste",
      "check-update": "les mises à jour disponibles",
      clean: "vide le cache",
      history: "l'historique",
    },
    operands: "les paquets",
    options: [opt("-y", "répond oui")],
  },
  {
    name: "yum",
    summary: "gère les paquets RHEL et CentOS (remplacé par dnf)",
    subcommands: {
      install: "installe",
      remove: "retire",
      update: "met à jour",
      search: "cherche",
      info: "la fiche",
      list: "liste",
    },
    operands: "les paquets",
    options: [opt("-y", "répond oui")],
  },
  {
    name: "pacman",
    summary: "gère les paquets Arch Linux",
    operands: "les paquets",
    options: [
      opt("-S", "installe (ou synchronise)"),
      opt("-Syu", "met tout à jour"),
      opt("-R", "retire"),
      opt("-Rs", "retire avec les dépendances inutiles"),
      opt("-Q", "interroge les paquets installés"),
      opt("-Ss", "cherche"),
      opt("-Qi", "la fiche d'un paquet installé"),
    ],
  },
  {
    name: "pip",
    summary: "installe des paquets Python",
    subcommands: {
      install: "installe",
      uninstall: "retire",
      list: "liste",
      freeze: "liste au format requirements.txt",
      show: "la fiche",
    },
    operands: "les paquets",
    options: [
      opt("-r", "installe la liste d'un fichier", "fichier"),
      opt("--user", "pour l'utilisateur seulement"),
      opt("-U --upgrade", "met à jour"),
    ],
  },
  {
    name: "pip3",
    summary: "installe des paquets Python 3",
    subcommands: {
      install: "installe",
      uninstall: "retire",
      list: "liste",
      freeze: "liste au format requirements.txt",
    },
    operands: "les paquets",
    options: [
      opt("-r", "installe la liste d'un fichier", "fichier"),
      opt("-U --upgrade", "met à jour"),
    ],
  },
  {
    name: "npm",
    summary: "gère les paquets Node.js",
    subcommands: {
      install: "installe (i)",
      i: "installe",
      uninstall: "retire",
      run: "lance un script du package.json",
      test: "lance les tests",
      start: "lance le projet",
      init: "crée un package.json",
      update: "met à jour",
      audit: "cherche des vulnérabilités connues",
      ls: "liste",
    },
    operands: "les paquets ou le script",
    options: [
      opt("-g --global", "pour toute la machine"),
      opt("-D --save-dev", "en dépendance de développement"),
      opt("--production", "sans les dépendances de développement"),
    ],
  },
  {
    name: "docker",
    summary: "pilote les conteneurs Docker",
    subcommands: {
      run: "crée et lance un conteneur depuis une image",
      ps: "liste les conteneurs qui tournent (-a : tous)",
      images: "liste les images",
      pull: "télécharge une image",
      build: "construit une image depuis un Dockerfile",
      exec: "exécute une commande dans un conteneur qui tourne",
      logs: "les journaux d'un conteneur",
      stop: "arrête un conteneur",
      start: "relance un conteneur",
      rm: "supprime un conteneur",
      rmi: "supprime une image",
      compose: "pilote plusieurs conteneurs décrits dans compose.yaml",
      inspect: "tout sur un conteneur ou une image",
      network: "les réseaux",
      volume: "les volumes",
      system: "l'espace et le nettoyage (system prune)",
    },
    operands: "l'image, le conteneur, puis la commande",
    options: [
      opt("-d --detach", "en arrière-plan"),
      opt("-p --publish", "publie un port : 8080:80", "hôte:conteneur"),
      opt("-v --volume", "monte un dossier : ./data:/data", "hôte:conteneur"),
      opt("-it", "interactif avec un terminal"),
      opt("-i", "interactif"),
      opt("-t", "avec un terminal"),
      opt("--name", "le nom du conteneur", "nom"),
      opt("--rm", "supprime le conteneur à l'arrêt"),
      opt("-e --env", "une variable d'environnement", "VAR=valeur"),
      opt("-a --all", "tous"),
      opt("-f --follow", "suit les journaux"),
      opt("--network", "le réseau", "réseau"),
    ],
  },
  {
    name: "git",
    summary: "gère l'historique d'un projet",
    subcommands: {
      init: "crée un dépôt",
      clone: "copie un dépôt distant",
      status: "l'état des fichiers : modifiés, indexés, non suivis",
      add: "indexe des fichiers pour le prochain commit",
      commit: "enregistre les fichiers indexés dans l'historique",
      log: "l'historique des commits",
      diff: "ce qui a changé et n'est pas encore indexé",
      branch: "les branches",
      checkout: "change de branche, ou restaure un fichier",
      switch: "change de branche",
      merge: "fusionne une branche dans la courante",
      rebase: "rejoue les commits sur une autre base",
      pull: "récupère et fusionne depuis le dépôt distant",
      push: "envoie les commits au dépôt distant",
      fetch: "récupère sans fusionner",
      stash: "met les modifications de côté",
      reset: "déplace la branche, et défait des commits",
      revert: "crée un commit qui annule un autre",
      tag: "les étiquettes de version",
      remote: "les dépôts distants",
      show: "le détail d'un commit",
      blame: "qui a écrit chaque ligne",
      restore: "restaure un fichier",
    },
    operands: "les fichiers, branches ou commits",
    options: [
      opt("-m --message", "le message du commit", "message"),
      opt("-a --all", "tous les fichiers suivis modifiés"),
      opt("-b", "crée la branche", "nom"),
      opt("--oneline", "une ligne par commit"),
      opt("--graph", "dessine les branches"),
      opt("-u --set-upstream", "retient la branche distante"),
      opt("--amend", "modifie le dernier commit"),
      opt("--hard", "jette aussi les modifications des fichiers"),
      opt("--soft", "garde les modifications indexées"),
      opt("-d", "supprime la branche", "nom"),
      opt("-p", "morceau par morceau"),
      opt("-v", "détaille"),
      opt("--force -f", "force"),
      opt("--staged --cached", "ce qui est indexé"),
    ],
  },

  // ── Shell ───────────────────────────────────────────────────────────────
  {
    name: "sh",
    summary: "lance un shell POSIX (ash sur BusyBox), ou exécute un script",
    operands: "le script à exécuter, puis ses arguments",
    options: [
      opt("-c", "exécute cette chaîne comme un script", "commande"),
      opt("-x", "affiche chaque commande avant de l'exécuter"),
      opt("-e", "s'arrête à la première erreur"),
      opt("-n", "vérifie la syntaxe sans exécuter"),
      opt("-u", "une variable non définie est une erreur"),
      opt("-i", "interactif"),
      opt("-l", "shell de connexion"),
    ],
  },
  {
    name: "bash",
    summary: "lance le shell bash, ou exécute un script",
    operands: "le script à exécuter, puis ses arguments",
    options: [
      opt("-c", "exécute cette chaîne comme un script", "commande"),
      opt("-x", "affiche chaque commande avant de l'exécuter"),
      opt("-e", "s'arrête à la première erreur"),
      opt("-n", "vérifie la syntaxe sans exécuter"),
      opt("-u", "une variable non définie est une erreur"),
      opt("-i", "interactif"),
      opt("-l --login", "shell de connexion"),
      opt("--norc", "sans lire .bashrc"),
      opt("--version", "la version"),
    ],
  },
  {
    name: "zsh",
    summary: "lance le shell zsh, ou exécute un script",
    operands: "le script, puis ses arguments",
  },
  {
    name: "source",
    summary: "exécute un script dans le shell courant : ses variables et fonctions restent",
    operands: "le fichier",
  },
  {
    name: ".",
    summary: "exécute un script dans le shell courant (comme source)",
    operands: "le fichier",
  },
  { name: "exec", summary: "remplace le shell par la commande", operands: "la commande" },
  {
    name: "exit",
    summary: "quitte le shell",
    operands: "le code de retour : 0 réussite, autre chose échec",
  },
  { name: "logout", summary: "quitte le shell de connexion" },
  { name: "clear", summary: "efface l'écran" },
  { name: "reset", summary: "remet le terminal en état après un affichage cassé" },
  {
    name: "history",
    summary: "les commandes tapées dans ce shell",
    operands: "N, les N dernières",
    options: [opt("-c", "efface l'historique"), opt("-d", "supprime l'entrée N", "N")],
  },
  {
    name: "alias",
    summary: "crée un raccourci de commande, ou liste ceux qui existent",
    operands: "nom='commande'",
  },
  {
    name: "unalias",
    summary: "supprime un raccourci",
    operands: "le nom",
    options: [opt("-a", "tous")],
  },
  {
    name: "export",
    summary: "rend une variable visible des programmes lancés depuis ce shell",
    operands: "VAR=valeur, ou VAR seule",
    options: [opt("-p", "liste les variables exportées"), opt("-n", "retire l'export", "VAR")],
  },
  {
    name: "unset",
    summary: "supprime une variable ou une fonction",
    operands: "les noms",
    options: [opt("-f", "une fonction"), opt("-v", "une variable")],
  },
  {
    name: "env",
    summary: "affiche l'environnement, ou lance une commande dans un environnement modifié",
    operands: "VAR=valeur, puis la commande",
    options: [
      opt("-i", "repart d'un environnement vide"),
      opt("-u", "retire cette variable", "VAR"),
    ],
  },
  {
    name: "printenv",
    summary: "affiche les variables d'environnement",
    operands: "une variable, pour sa valeur seule",
  },
  {
    name: "set",
    summary: "règle le shell, ou affiche ses variables",
    operands: "les options : -e, -x, -u, -o pipefail",
    options: [
      opt("-e", "s'arrête à la première erreur"),
      opt("-x", "affiche chaque commande avant de l'exécuter"),
      opt("-u", "une variable non définie est une erreur"),
      opt("-o", "une option par son nom : pipefail, noclobber", "option"),
      opt("+x", "cesse d'afficher les commandes"),
    ],
  },
  {
    name: "read",
    summary: "lit une ligne au clavier dans une variable",
    operands: "la variable",
    options: [
      opt("-p", "affiche cette invite", "texte"),
      opt("-s", "sans écho (mot de passe)"),
      opt("-r", "sans interpréter les antislashs"),
      opt("-n", "N caractères, sans attendre Entrée", "N"),
      opt("-t", "abandonne après N secondes", "N"),
    ],
  },
  {
    name: "test",
    summary: "évalue une condition : fichier, chaîne, nombre (vrai : code 0)",
    operands: "-f fichier existe, -d dossier existe, -z chaîne vide, a = b, n -eq m, n -gt m",
  },
  { name: "[", summary: "test, écrit entre crochets", operands: "la condition, puis ]" },
  {
    name: "[[",
    summary: "test étendu de bash : motifs, regex (=~), && et || dedans",
    operands: "la condition, puis ]]",
  },
  { name: "true", summary: "ne fait rien et réussit (code 0)" },
  { name: "false", summary: "ne fait rien et échoue (code 1)" },
  {
    name: "seq",
    summary: "affiche une suite de nombres",
    operands: "la fin, ou début fin, ou début pas fin",
    options: [opt("-s", "le séparateur", "texte"), opt("-w", "complète avec des zéros")],
  },
  {
    name: "yes",
    summary: "répète un mot sans fin (oui par défaut), pour répondre à une commande",
    operands: "le mot",
  },
  {
    name: "basename",
    summary: "le nom de fichier sans son chemin",
    operands: "le chemin, puis un suffixe à retirer",
  },
  { name: "dirname", summary: "le chemin sans le nom de fichier", operands: "le chemin" },
  { name: "realpath", summary: "le chemin absolu, liens résolus", operands: "le chemin" },
  {
    name: "type",
    summary:
      "dit ce qu'est un mot pour le shell : commande interne, alias, fonction, ou programme et où",
    operands: "les noms",
    options: [opt("-a", "toutes les possibilités"), opt("-t", "le type seul")],
  },
  {
    name: "which",
    summary: "où est le programme que le shell lancerait pour ce nom",
    operands: "les noms",
    options: [opt("-a", "toutes les occurrences dans le PATH")],
  },
  {
    name: "whereis",
    summary: "où sont le programme, ses sources et son manuel",
    operands: "les noms",
  },
  {
    name: "command",
    summary: "lance la commande en ignorant alias et fonctions",
    operands: "la commande",
    options: [opt("-v", "dit où elle est, sans la lancer")],
  },
  {
    name: "man",
    summary: "le manuel d'une commande (q pour quitter, / pour chercher)",
    operands: "la commande, ou une section puis la commande : man 5 passwd",
    options: [
      opt("-k", "cherche dans les descriptions", "mot"),
      opt("-f", "la description en une ligne", "commande"),
    ],
  },
  { name: "help", summary: "l'aide d'une commande interne du shell", operands: "la commande" },
  { name: "info", summary: "la documentation détaillée d'une commande", operands: "la commande" },
  {
    name: "whatis",
    summary: "la description en une ligne d'une commande",
    operands: "la commande",
  },
  { name: "apropos", summary: "cherche une commande par mots-clés", operands: "les mots" },
  {
    name: "xdg-open",
    summary: "ouvre un fichier ou une URL avec l'application par défaut",
    operands: "le fichier ou l'URL",
  },
  {
    name: "shellcheck",
    summary: "relit un script shell et signale les pièges",
    operands: "les scripts",
    options: [
      opt("-s", "le dialecte : sh, bash", "shell"),
      opt("-e", "ignore ces avertissements", "codes"),
      opt("-f", "le format de sortie", "format"),
    ],
  },
  {
    name: "make",
    summary: "construit un projet selon son Makefile",
    operands: "la cible : all, install, clean",
    options: [
      opt("-j", "N tâches en parallèle", "N"),
      opt("-f", "ce Makefile", "fichier"),
      opt("-n", "montre les commandes sans les lancer"),
      opt("-C", "dans ce dossier", "dossier"),
    ],
  },
  {
    name: "gcc",
    summary: "compile du C",
    operands: "les fichiers source",
    options: [
      opt("-o", "le fichier produit", "fichier"),
      opt("-Wall", "tous les avertissements utiles"),
      opt("-Wextra", "des avertissements en plus"),
      opt("-g", "avec les informations de débogage"),
      opt("-O2", "optimise"),
      opt("-c", "compile sans lier (produit un .o)"),
      opt("-l", "lie cette bibliothèque : -lm", "bibliothèque"),
      opt("-I", "un dossier d'en-têtes", "dossier"),
      opt("-std", "la norme : -std=c11", "norme"),
      opt("-fsanitize", "un détecteur à l'exécution : address, undefined", "détecteur"),
    ],
  },
  {
    name: "gdb",
    summary: "le débogueur",
    operands: "le programme, puis un core",
    options: [
      opt("-q", "sans la bannière"),
      opt("--args", "le programme avec ses arguments"),
      opt("-batch", "exécute et quitte"),
      opt("-ex", "une commande gdb à exécuter", "commande"),
    ],
  },
  {
    name: "nasm",
    summary: "assemble du code x86",
    operands: "le fichier source",
    options: [
      opt("-f", "le format : elf64, elf32, bin", "format"),
      opt("-o", "le fichier produit", "fichier"),
      opt("-g", "avec les informations de débogage"),
      opt("-l", "produit un listing", "fichier"),
    ],
  },
  {
    name: "ld",
    summary: "l'éditeur de liens : assemble des objets en exécutable",
    operands: "les fichiers objets",
    options: [
      opt("-o", "le fichier produit", "fichier"),
      opt("-m", "l'émulation : elf_x86_64", "émulation"),
      opt("-l", "lie cette bibliothèque", "bibliothèque"),
    ],
  },
  {
    name: "objdump",
    summary: "désassemble ou examine un binaire",
    operands: "le fichier",
    options: [
      opt("-d", "désassemble le code"),
      opt("-M", "la syntaxe : intel", "syntaxe"),
      opt("-x", "tous les en-têtes"),
      opt("-h", "les sections"),
      opt("-s", "le contenu des sections"),
    ],
  },
  {
    name: "ltrace",
    summary: "trace les appels de bibliothèque d'un programme",
    operands: "le programme",
  },
  {
    name: "strace",
    summary: "trace les appels système d'un programme",
    operands: "le programme",
    options: [
      opt("-p", "s'attache à ce processus", "PID"),
      opt("-e", "ces appels seulement : -e trace=open,read", "filtre"),
      opt("-o", "écrit la trace dans ce fichier", "fichier"),
      opt("-f", "suit aussi les processus fils"),
      opt("-c", "un résumé par appel"),
    ],
  },
  {
    name: "lsof",
    summary: "les fichiers ouverts, et par qui",
    options: [
      opt("-i", "les connexions réseau : -i :80, -i tcp", "filtre"),
      opt("-p", "ceux de ce processus", "PID"),
      opt("-u", "ceux de cet utilisateur", "utilisateur"),
      opt("-n", "sans résolution de noms"),
      opt("-P", "sans résolution des ports"),
    ],
  },
  {
    name: "python3",
    summary: "lance l'interpréteur Python 3, ou un script",
    operands: "le script, puis ses arguments",
    options: [
      opt("-c", "exécute ce code", "code"),
      opt("-m", "lance un module : -m http.server, -m venv", "module"),
      opt("-i", "interactif après le script"),
      opt("-u", "sans tampon de sortie"),
      opt("-V --version", "la version"),
    ],
  },
  {
    name: "python",
    summary: "lance l'interpréteur Python, ou un script",
    operands: "le script, puis ses arguments",
    options: [
      opt("-c", "exécute ce code", "code"),
      opt("-m", "lance un module", "module"),
      opt("-V --version", "la version"),
    ],
  },
  {
    name: "node",
    summary: "lance Node.js, ou un script JavaScript",
    operands: "le script, puis ses arguments",
    options: [
      opt("-e", "exécute ce code", "code"),
      opt("-v --version", "la version"),
      opt("--watch", "relance quand le fichier change"),
    ],
  },
  {
    name: "php",
    summary: "lance l'interpréteur PHP, ou un script",
    operands: "le script",
    options: [
      opt("-r", "exécute ce code", "code"),
      opt("-S", "un serveur web de développement : -S localhost:8000", "hôte:port"),
      opt("-l", "vérifie la syntaxe"),
      opt("-v", "la version"),
      opt("-m", "les modules chargés"),
    ],
  },
  {
    name: "vi",
    summary:
      "l'éditeur vi : i pour insérer, Échap, :wq pour enregistrer et quitter, :q! pour quitter sans enregistrer",
    operands: "le fichier",
  },
  {
    name: "vim",
    summary:
      "l'éditeur vim : i pour insérer, Échap, :wq pour enregistrer et quitter, :q! pour abandonner",
    operands: "le fichier",
  },
  {
    name: "nano",
    summary: "l'éditeur nano : Ctrl+O enregistre, Ctrl+X quitte",
    operands: "le fichier",
    options: [opt("-l", "numérote les lignes"), opt("-w", "ne replie pas les lignes longues")],
  },
  {
    name: "busybox",
    summary: "le couteau suisse : une commande qui en contient des dizaines",
    operands: "la commande à lancer, puis ses arguments",
  },
  {
    name: "ldd",
    summary: "les bibliothèques partagées dont un programme a besoin",
    operands: "le programme",
  },
  { name: "lsns", summary: "liste les espaces de noms (conteneurs)" },
  {
    name: "chroot",
    summary: "lance une commande avec ce dossier comme racine",
    operands: "le dossier, puis la commande",
  },
  {
    name: "mokutil",
    summary: "gère les clés du démarrage sécurisé (Secure Boot)",
    options: [
      opt("--sb-state", "l'état du Secure Boot"),
      opt("--list-enrolled", "les clés enregistrées"),
    ],
  },
  {
    name: "efibootmgr",
    summary: "les entrées de démarrage UEFI",
    options: [opt("-v", "détaille"), opt("-o", "l'ordre de démarrage", "liste")],
  },
  { name: "update-grub", summary: "régénère la configuration du chargeur GRUB" },
  {
    name: "grub-install",
    summary: "installe le chargeur GRUB sur un disque",
    operands: "le disque",
  },
  { name: "inetd", summary: "le super-serveur qui lance un service à chaque connexion" },
  {
    name: "service",
    summary: "pilote un service (l'ancienne commande, qui renvoie à systemctl)",
    operands: "le service, puis start, stop, restart, status",
  },
  {
    name: "ssh-keyscan",
    summary: "récupère la clé publique d'un serveur SSH",
    operands: "la machine",
    options: [opt("-t", "le type de clé", "type"), opt("-p", "le port", "port")],
  },
  {
    name: "wall",
    summary: "envoie un message à tous les utilisateurs connectés",
    operands: "le message",
  },
  {
    name: "write",
    summary: "envoie un message à un utilisateur connecté",
    operands: "l'utilisateur",
  },
  {
    name: "mesg",
    summary: "autorise ou refuse les messages des autres utilisateurs",
    operands: "y ou n",
  },
  {
    name: "script",
    summary: "enregistre tout ce qui s'affiche dans le terminal",
    operands: "le fichier d'enregistrement",
  },
  {
    name: "tmux",
    summary: "un multiplexeur de terminaux : plusieurs fenêtres, détachables",
    subcommands: {
      new: "une nouvelle session (-s nom)",
      attach: "rattache une session (-t nom)",
      ls: "liste les sessions",
      "kill-session": "termine une session",
      detach: "détache",
    },
  },
  {
    name: "screen",
    summary: "un multiplexeur de terminaux, détachable",
    options: [
      opt("-S", "le nom de la session", "nom"),
      opt("-r", "rattache une session"),
      opt("-ls", "liste les sessions"),
      opt("-d", "détache"),
    ],
  },
];

export const COMMAND_BY_NAME: ReadonlyMap<string, CommandSpec> = new Map(
  COMMANDS.map((spec) => [spec.name, spec]),
);

export function commandSpec(name: string): CommandSpec | undefined {
  return COMMAND_BY_NAME.get(name);
}
