"use server";

import crypto from "node:crypto";
import { renderToBuffer } from "@react-pdf/renderer";
import QRCode from "qrcode";
import {
  prisma,
  pathRepository,
  certificateRepository,
  notificationRepository,
  badgeRepository,
  userRepository,
} from "@cyberlearn/db";
import { createSupabaseAdminClient } from "@cyberlearn/db/supabase/admin";
import { evaluateBadges } from "@cyberlearn/lib";
import { CertificateDocument } from "@/lib/pdf/certificate-template";

const APP_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://cyberlearn.fr";
const BUCKET = "certificates";

async function generateCertificate(userId: string, pathId: string): Promise<string | null> {
  const [user, path] = await Promise.all([
    prisma.user.findUnique({ where: { id: userId }, select: { displayName: true } }),
    prisma.path.findUnique({ where: { id: pathId }, select: { title: true } }),
  ]);

  if (!user || !path) return null;

  const issuedAt = new Date();
  // publicId generated by Prisma default, we create the record first to get it
  const certRecord = await certificateRepository.create({
    userId,
    pathId,
    sha256Hash: "pending", // filled after PDF generation
    pdfStorageKey: "pending",
  });

  const verifyUrl = `${APP_URL}/verify/${certRecord.publicId}`;
  const qrCodeDataUrl = await QRCode.toDataURL(verifyUrl, { width: 200, margin: 1 });

  const pdfBuffer = await renderToBuffer(
    <CertificateDocument
      displayName={user.displayName}
      pathTitle={path.title}
      issuedAt={issuedAt}
      publicId={certRecord.publicId}
      sha256Hash=""
      qrCodeDataUrl={qrCodeDataUrl}
      appUrl={APP_URL}
    />,
  );

  const sha256Hash = crypto.createHash("sha256").update(pdfBuffer).digest("hex");
  const storageKey = `${userId}/${certRecord.id}.pdf`;

  // Upload to Supabase Storage
  const supabase = createSupabaseAdminClient();
  await supabase.storage.from(BUCKET).upload(storageKey, pdfBuffer, {
    contentType: "application/pdf",
    cacheControl: "public, max-age=31536000, immutable",
    upsert: false,
  });

  // Update certificate record with real hash + storage key
  await prisma.certificate.update({
    where: { id: certRecord.id },
    data: { sha256Hash, pdfStorageKey: storageKey },
  });

  return certRecord.id;
}

/** Called after a lesson is completed. Checks all paths containing that lesson for 100% completion. */
export async function checkAndIssueCertificates(userId: string, lessonId: string): Promise<void> {
  const paths = await pathRepository.findPublishedPathsForLesson(lessonId);
  if (paths.length === 0) return;

  for (const path of paths) {
    const [totalIds, completedCount, existing] = await Promise.all([
      pathRepository.findLessonIds(path.id),
      pathRepository.countCompletedLessons(userId, path.id),
      pathRepository.findProgress(userId, path.id),
    ]);

    if (completedCount < totalIds.length) continue;
    if (existing?.status === "COMPLETED") continue;

    const certId = await generateCertificate(userId, path.id);

    if (certId) {
      await pathRepository.linkCertificate(userId, path.id, certId);

      // Notify: path completed + certificate issued
      await Promise.all([
        notificationRepository.create({
          userId,
          type: "PATH_COMPLETED",
          title: `Parcours terminé : ${path.title}`,
          body: "Félicitations ! Tu as complété tous les modules de ce parcours.",
          actionUrl: `/paths/${path.slug}`,
        }),
        notificationRepository.create({
          userId,
          type: "CERTIFICATE_ISSUED",
          title: "Certificat émis",
          body: `Ton certificat pour "${path.title}" est disponible.`,
          actionUrl: `/api/certificates/${certId}/download`,
          metadata: { certId, pathTitle: path.title },
        }),
      ]);
    } else {
      // Certificate generation failed — still mark path as complete
      await pathRepository.upsertProgress({
        userId,
        pathId: path.id,
        status: "COMPLETED",
        completedAt: new Date(),
      });

      // Notify: path completed without certificate
      await notificationRepository.create({
        userId,
        type: "PATH_COMPLETED",
        title: `Parcours terminé : ${path.title}`,
        body: "Félicitations ! Tu as complété tous les modules de ce parcours.",
        actionUrl: `/paths/${path.slug}`,
      });
    }

    // Evaluate PATH_COMPLETED badges now that this path is complete
    await awardPathCompletedBadges(userId, path.id);
  }
}

/** Evaluates and awards any PATH_COMPLETED badges triggered by a newly completed path. */
async function awardPathCompletedBadges(userId: string, pathId: string): Promise<void> {
  const [allBadges, earnedIds, user, lessonCounts, totalCertificates] = await Promise.all([
    badgeRepository.findAllActive(),
    badgeRepository.findUserBadgeIds(userId),
    userRepository.findForGamification(userId),
    userRepository.countCompletedLessonsByCategory(userId),
    prisma.certificate.count({ where: { userId } }),
  ]);

  if (!user || allBadges.length === 0) return;

  const newBadgeIds = evaluateBadges(allBadges, earnedIds, {
    xpTotal: user.xpTotal,
    streakDays: user.streakDays,
    totalLessonsCompleted: lessonCounts.total,
    categoryLessonCounts: lessonCounts.byCategory,
    completedPathId: pathId,
    totalCertificates,
  });

  if (newBadgeIds.length === 0) return;

  const earnedBadges = allBadges.filter((b) => newBadgeIds.includes(b.id));
  await prisma.$transaction([
    prisma.userBadge.createMany({
      data: newBadgeIds.map((badgeId) => ({ userId, badgeId, context: { pathId } })),
      skipDuplicates: true,
    }),
    prisma.notification.createMany({
      data: earnedBadges.map((badge) => ({
        userId,
        type: "BADGE_EARNED" as const,
        title: `Badge obtenu : ${badge.name}`,
        body: badge.description,
        actionUrl: "/badges",
        metadata: { badgeId: badge.id, rarity: badge.rarity as string },
      })),
    }),
  ]);
}
